### PR TITLE
make zookeeper jar as provided, as its included in classpath from hba…

### PR DESCRIPTION
**Pull request by gsps1**
…se classpath

### CODE REVIEW

**Comment by gsps1** [comment]
build running : http://builds.cask.co/browse/CDAP-RBT322-1

**Comment by ghelmling** [comment]
Hmm, better test that this still works for standalone as well.

**Comment by gsps1** [comment]
tested on standalone as well.

**Comment by ghelmling** [comment]
lgtm, assuming test build passes and testing on a cluster works as well.

**Pull request merged**
