### PR TITLE
Update v3 version endpoint

### PR DESCRIPTION
**Pull request by sreevatsanraman**
* Added v3/version endpoint

http://builds.cask.co/browse/CDAP-DUT1237

### CODE REVIEW

**Comment by albertshau** [comment]
:+1:

**Comment by sreevatsanraman** [comment]
[sree@mac ~]$ curl http://127.0.0.1:10000/v3/version
{"version":"2.8.0-SNAPSHOT"}[sree@mac ~]$ 
[sree@mac ~]$ 
[sree@mac ~]$ curl http://127.0.0.1:10000/v2/version
{"version":"2.8.0-SNAPSHOT"}[sree@mac ~]$ 
[sree@mac ~]$

**Comment by sreevatsanraman** [comment]
Will merge once the build passes.

**Comment by sreevatsanraman** [comment]
Build passed. Merging

**Pull request merged**
