### PR TITLE
[CDAP-2690] change View Queries to View Results

### PR DESCRIPTION
**Pull request by elfenheart**
screen shot 2015-07-02 at 5 09 17 pm
screen shot 2015-07-02 at 5 09 46 pm

### CODE REVIEW

**Comment by bdmogal** [comment]
Should we change this to 'Preview Results'?

**Comment by ajainarayanan** [comment]
@bdmogal We discussed about this. Fellback to "View Results" finally. Might want to get a final word from @nitinmotgi before merging this PR. Otherwise :+1: LGTM

**Comment by bdmogal** [comment]
Oh! I think I got it wrong. Its fine for **View Results** to be as-is. I was referring to the **Results** heading here: https://s3.amazonaws.com/uploads.hipchat.com/26476/2151142/MauTFo10Zpze1lK/upload.png

**Comment by elfenheart** [comment]
Talked to @nitinmotgi and confirmed changing Results to Preview

screen shot 2015-07-07 at 5 43 46 pm

**Comment by bdmogal** [comment]
:+1:

**Pull request merged**
