### PR TITLE
CDAP-2387 Register shutdown hook to stop Log Saver before Hadoop Filesystem

### PR DESCRIPTION
**Pull request by poornachandra**
JIRA https://issues.cask.co/browse/CDAP-2387

### CODE REVIEW

**Comment by poornachandra** [comment]
Build - http://builds.cask.co/browse/CDAP-RBT251-2

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Comment by poornachandra** [comment]
Build - http://builds.cask.co/browse/CDAP-RBT251-3

**Comment by poornachandra** [comment]
Merging since a test un-releated to the changes in PR is failing. Also, cdap-watchdog tests ran successfully.

**Pull request merged**
