### PR TITLE
Fix the external plugin id due to fix to support multiple JMS providers.

### PR DESCRIPTION
**Pull request by henry-cask**
Fix the external plugin id due to fix to support multiple JMS providers.

### CODE REVIEW

**Comment by henry-cask** [comment]
CC @albertshau Fix for develop branch

**Comment by henry-cask** [comment]
http://builds.cask.co/browse/CDAP-DUT1989-1

**Comment by albertshau** [comment]
lgtm

**Comment by henry-cask** [comment]
Thanks, will merge once build pass

**Pull request merged**
