### PR TITLE
Check Runrecord with retries

### PR DESCRIPTION
**Pull request by sreevatsanraman**
* Fix randomness in test failure by testing with retries.

### CODE REVIEW

**Comment by bdmogal** [comment]
:+1:

**Comment by bdmogal** [comment]
Can you add jira to the commit message before merging?

**Comment by sreevatsanraman** [comment]
http://builds.cask.co/browse/CDAP-DUT1615-1

**Comment by sreevatsanraman** [comment]
JIRA: https://issues.cask.co/browse/CDAP-2232

**Comment by sreevatsanraman** [comment]
Un related test failure. Merging this

**Pull request merged**
