### PR TITLE
CDAP-2034: Removed unnecessary actions in AdapterClientTest, as StandaloneTestBase takes care of cleanup already

### PR DESCRIPTION
**Pull request by jwang47**
https://issues.cask.co/browse/CDAP-2034
http://builds.cask.co/browse/CDAP-DUT1365

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Comment by gokulavasan** [comment]
How does this resolve the problem?

**Comment by jwang47** [comment]
AdapterClientTest doesn't stop any programs, so if the adapter workflow starts before deleteAll is called, then we get the exception "program still running". I removed that part of the test, since StandaloneTestBase does stop all programs and unrecoverable reset in @AfterClass.

**Comment by gokulavasan** [comment]
Ok so even if MR job is running, the cleanup in StandaloneTestBase do the required cleanup. Thanks Alvin!

**Pull request merged**
