### PR TITLE
Authorization parent

### PR DESCRIPTION
**Pull request by jwang47**
This is the parent PR for authorization. It includes

* https://github.com/caskdata/cdap/pull/1309 Authorization core (feature/authorization-core)
* https://github.com/caskdata/cdap/pull/1311 Dataset implementation of ACLStore (feature/authorization-cdap)
* https://github.com/caskdata/cdap/pull/1312 CLI support for authorization (feature/authorization-cli)
* https://github.com/caskdata/cdap/pull/1314 Authorization for application and program endpoints (feature/authorization-apps)

TODO
- [ ] Documentation
- [ ] Deploying app should grant the user ADMIN permission on that app
- [ ] Give 404 instead of 401 to users trying to make calls to X endpoint when user shouldn't know that X exists

### CODE REVIEW

**Comment by jwang47** [comment]
Might make more sense to use Apache Shiro's ACL representation rather than the one I've implemented in the PRs. We'd be combining object and permission into one string, and we wouldn't have rigid permission types that we try to force our various components to use. See https://github.com/apache/shiro/blob/1.0.x/core/src/test/java/org/apache/shiro/authz/permission/WildcardPermissionTest.java for an example of Shiro's permissions.

Closing the child PRs until we make a decision about this.

**Comment by jwang47** [comment]
Decided to continue with what we have currently.

**Comment by ghelmling** [comment]
What is the purpose of this PR?  It has no changes...

Can we close it in favor of the "child" PRs that it describes?

**Comment by jwang47** [comment]
I opened the child PRs against this branch, so once all the child PRs are merged, I'll merge this one into develop.

**Comment by jwang47** [comment]
Deprioritizing security for now, so closing.

**Pull request closed without merging**
