### PR TITLE
Refactor Metadata Tags Code

### PR DESCRIPTION
**Pull request by elfenheart**

### CODE REVIEW

**Comment by ajainarayanan** [comment]
The changes look good. But found this jittery stuff when playing around with the tags. I think we had this from the beginning. Can we have the 'x' icon appear over the text so that the width doesn't exceed causing elements to move left and right when user hovers over the mouse.

tags

**Comment by ajainarayanan** [comment]
Otherwise :+1: LGTM

**Comment by elfenheart** [comment]
The problem with that is that when later we change the behavior of the tags to become links, we won't be able to click the tags as link..we can only remove them

**Comment by ajainarayanan** [comment]
:+1: LGTM

**Pull request merged**
