### PR TITLE
Moved all exception classes to co.cask.cdap.common from co.cask.cdap.…

### PR DESCRIPTION
**Pull request by bdmogal**
…common.exceptions

This is in keeping with Java standard of having exceptions in java.lang as opposed to java.lang.exception

Build: http://builds.cask.co/browse/CDAP-DUT2098

### CODE REVIEW

**Comment by bdmogal** [comment]
Build is :green_apple:

**Comment by jwang47** [comment]
LGTM

**Comment by bdmogal** [comment]
Rebased to resolve merge conflicts. 

New Build: http://builds.cask.co/browse/CDAP-DUT2155-1

Will merge after build passes.

**Comment by bdmogal** [comment]
Build passed. Merging.

**Pull request merged**
