### PR TITLE
(CDAP-1709) Wait for the mini DFS to come up before using it

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by chtyim** [comment]
Build running http://builds.cask.co/browse/CDAP-RBT561-1

**Comment by anwar6953** [comment]
LGTM

**Comment by anwar6953** [comment]
Build failed - http://builds.cask.co/browse/CDAP-RBT561-1
I restarted it, checking if its deterministic or not.

**Comment by sreevatsanraman** [comment]
Build passed. Merging.

**Pull request merged**
