### PR TITLE
Move ElasticPoolTest into tephra project.

### PR DESCRIPTION
**Pull request by anwar6953**
Here's a JIRA to move it into tephra codebase:
https://issues.cask.co/browse/CDAP-4148

http://builds.cask.co/browse/CDAP-DUT3058-1

### CODE REVIEW

**Comment by albertshau** [comment]
:+1:

**Comment by anew** [comment]
LGTM. Can you link this to the corresponding Tephra-issue?

**Comment by anwar6953** [comment]
PR to move it into tephra Project: https://github.com/caskdata/tephra/pull/99

**Comment by chtyim** [comment]
Merging this. This breaks all feature branches.

**Pull request merged**
