### PR TITLE
CDAP-5784 Upgrade steps have hydrator upgrade as the wrong step

### PR DESCRIPTION
**Pull request by awholegunch**
Reverse last two steps of upgrade process.

Fix for https://issues.cask.co/browse/CDAP-5784

Passes [Quick Build 3](http://builds.cask.co/browse/CDAP-DOB189-3).

### CODE REVIEW

**Comment by albertshau** [comment]
lgtm

**Comment by rohitsinha54** [comment]
LGTM

**Comment by awholegunch** [comment]
Will merge once I get a clean doc build.

**Comment by awholegunch** [comment]
Found a few more "3.2.x" that needed versioning.

**Comment by albertshau** [comment]
lgtm

**Pull request merged**
