### PR TITLE
adds cursor on hover to table links

### PR DESCRIPTION
**Pull request by astewes**
*  Adds cursor: pointer on hover to table links

tables

### CODE REVIEW

**Comment by anwar6953** [comment]
LGTM.
though is it the case that other links don't need this special css to make the pointer appear?

**Comment by awholegunch** [comment]
+100

**Comment by astewes** [comment]
@anwar6953 i've searched cdap-ui and didn't find any additional CSS that would need to be removed as a result of this change.

**Comment by anwar6953** [comment]
What I meant is - how come other links don't require this type of css, in order for the pointer to change on hover?

**Comment by astewes** [comment]
@anwar6953 in this instance, it's due to 1) an ng-click being applied to the \<a\> tag, 2) neither href or ui-sref attributes being used. where \<a\> tags are concerned, this isn't something done very often, but it's especially confusing when displaying a table of links, as there's no visual indication that the text contains a hyperlink.

**Comment by anwar6953** [comment]
oh ok; lgtm.

**Pull request merged**
