### PR TITLE
CDAP-2030 Automate VM build

### PR DESCRIPTION
**Pull request by wolf31o2**
- Import preseed [file](https://help.ubuntu.com/12.04/installation-guide/example-preseed.txt) from Ubuntu and configure
- JSON template for [packer](http://packer.io)
- Small scripts for setting up the VM (X.org, Firefox, fluxbox, CDAP SDK, etc)

### CODE REVIEW

**Comment by duddun** [comment]
LGTM

**Comment by nitinmotgi** [comment]
Does it have intellij or eclipse. We should create one with intellij and eclipse. We can start with eclipse.

**Comment by wolf31o2** [comment]
Currently, it has IntelliJ... I can work on eclipse support.

**Comment by wolf31o2** [comment]
I am going to merge this. We can make modifications to it in another iteration, such as adding eclipse.

**Pull request merged**
