### PR TITLE
(CDAP-5650) Have test base services always bind to localhost

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by chtyim** [comment]
Tried removing the preferIPv4Stack property and running it in bamboo to see if it covers everything.

Verify locally on test cases that are known to be affected by it.

**Comment by chtyim** [comment]
Build running in http://builds.cask.co/browse/CDAP-DUT4033-1

**Comment by albertshau** [comment]
lgtm assuming all tests are green

**Comment by wolf31o2** [comment]
Is this because our tests were connecting to `localhost` as a client, and sometimes that was resolving to an IPv6 address (::1) versus IPv4?

**Comment by chtyim** [comment]
@wolf31o2 It's because the `TestBase` uses `0.0.0.0` (from cdap-default.xml) and it will get resolved to IPv6 address on some box.

**Comment by anwar6953** [comment]
Can you also remove other occurrences of `-Djava.net.preferIPv4Stack=true` from the project?
For instance:
https://github.com/caskdata/cdap/blob/release/3.4/cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/pom.xml#L190-190

**Comment by chtyim** [comment]
Build passed.

**Comment by chtyim** [comment]
I'll remove the one from archetype, but won't run the build again as it's a resources, hence won't affect the test.

**Pull request merged**
