### PR TITLE
Docs/3.2 cleanup

### PR DESCRIPTION
**Pull request by awholegunch**
Fixes numerous problems with references to "Application Templates" and "Adapters" in the documentation.

**Revises the "Introduction to CDAP" exercise.**
- Updates it for 3.2.0. 
- Corrects a number of mistakes in the commands and the output. 
- Changes the formatting to make it easier to see the commands by putting in a **"cdap >"** prompt before each CLI command.
- Commands have been run manually against the 3.2.0 SDK.
- There are so many changes, GitHub is not providing a diff. Sorry.
- [Rendered revised "Introduction to CDAP"](http://builds.cask.co/artifact/CDAP-DOB4/shared/build-1/Docs-HTML/3.2.0/en/introduction/index.html)

Documentation has passed the [Quick Build](http://builds.cask.co/browse/CDAP-DOB4-1).
Full documentation building: http://builds.cask.co/browse/CDAP-DDB25-1

Partial Fix for https://issues.cask.co/browse/CDAP-3891

### CODE REVIEW

**Comment by anwar6953** [comment]
For this file: cdap/cdap-docs/introduction/source/index.rst
you sometimes back HDFS bold and sometimes don't, even though the context is similar.
For instance, see lines: 138 vs 166

(its difficult to put this as a comment on that file, because the diff isn't visible in this GitHub PR.

**Comment by jwang47** [comment]
Not sure why cdap-docs/introduction/source/index.rst isn't visible here, but changes other than that LGTM.

**Comment by anwar6953** [comment]
For this file: cdap/cdap-docs/introduction/source/index.rst
Line 1310 is missing a `'` mark at the end of the line.

**Comment by anwar6953** [comment]
RE: https://github.com/caskdata/cdap/blame/docs/3.2_cleanup/cdap-docs/introduction/source/index.rst#L1586

The actual url to hit is:
`http://hostname:port/v3/namespaces/default/apps/Wise/services/WiseService/methods/ip/69.181.160.120/count`

**Comment by anwar6953** [comment]
RE: https://github.com/caskdata/cdap/blame/docs/3.2_cleanup/cdap-docs/introduction/source/index.rst#L1807

Does this sound better:
`Services and tools that enable faster application development`

**Comment by awholegunch** [comment]
I have picked up all these suggestions and fixes and incorporated them. The bolding of the **HDFS** (and other technologies) was to have the first usage of them in each section be in bold, as a way of emphasizing all the different technologies required. As it looks like that was appearing inconsistent and arbitrary (if the pattern isn't obvious, then it isn't working as a pattern), I've made them all bold...

**Comment by awholegunch** [comment]
Revised: 
- [Quick Build](http://builds.cask.co/browse/CDAP-DOB4-2)
- [Rendered revised "Introduction to CDAP"](http://builds.cask.co/artifact/CDAP-DOB4/shared/build-1/Docs-HTML/3.2.0/en/introduction/index.html)

**Comment by anwar6953** [comment]
LGTM

**Pull request merged**
