### PR TITLE
Feature/cdap 1574 ds upgrade

### PR DESCRIPTION
**Pull request by anew**
Cherry-picked the commit from CDAP-1253 into this branch and resolved all conflicts.

### CODE REVIEW

**Comment by anew** [comment]
Build passes here: http://builds.cask.co/browse/CDAP-DUT991-4

**Comment by albertshau** [comment]
lgtm.  Are we documenting this at all?

**Comment by anew** [comment]
Not sure. It was undocumented in 2.6.1. @poornachandra @sreevatsanraman what do you think?

**Comment by anew** [comment]
I will merge this now and possibly add documentation in a new PR

**Comment by ParthGandhi** [comment]
We did add some release notes that explained this property: https://github.com/caskdata/cdap/pull/1179

Maybe we want add them for this release too? Or move them to documentation under a small section?

**Comment by anew** [comment]
See CDAP-1700.

**Pull request merged**
