### PR TITLE
Cube Dataset Developers' Manual and Guide

### PR DESCRIPTION
**Pull request by awholegunch**
Adds the new Cube Dataset Guide to the Examples Manual.
Adds info on Cube Datasets to the Developers' Manual
Adds a new echo statement to the common build script that prints in red bold font.

Staged at:
- [Guides List](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-r3.0_Cube_Dataset_Guide/en/examples-manual/how-to-guides/index.html)
- [Data Analysis with OLAP Cube](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-r3.0_Cube_Dataset_Guide/en/examples-manual/how-to-guides/cdap-cube-guide.html)
- [Datasets](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-r3.0_Cube_Dataset_Guide/en/developers-manual/building-blocks/datasets/index.html)
- [Cube Datasets](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-r3.0_Cube_Dataset_Guide/en/developers-manual/building-blocks/datasets/cube.html)

### CODE REVIEW

**Comment by abaranau** [comment]
http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-r3.0_Cube_Dataset_Guide/en/developers-manual/building-blocks/datasets/cube.html is empty

**Comment by awholegunch** [comment]
Ready to be reviewed.

**Comment by abaranau** [comment]
"Additionally, Cube datasets allows for exploring of the data stored in the Cube" - no link to SQL for exploring word.

**Comment by abaranau** [comment]
Why change colors on diagrams? First one is ok, but second - it mixes stuff, no?

**Comment by abaranau** [comment]
Also, in the images I used - there was syntax highlight...

**Comment by abaranau** [comment]
"Here is an example:" - can we say it is an analogy or smth like that? Otherwise from text it feels like you can use SQL to do those things

**Comment by abaranau** [comment]
"A Cube can have multiple configured views and they can be altered by updating the dataset properties using the Dataset RESTful API." - should not be in one sentence. Confusing.

**Comment by abaranau** [comment]
"based on the dataset.cube.resolutions property, which takes a value in seconds, such as 1, 60, or 3600 (corresponding to 1 second, 1 minute, or 1 hour resolutions)"

which takes a comma-seprated list of resolutions in seconds

**Comment by abaranau** [comment]
In the original doc:

> e.g.:

> dataset.cube.resolutions=1,60,3600

> configures 1 second, 1 minute and 1 hour resolutions.

Let's keep this example

**Comment by abaranau** [comment]
"Querying data in Cube dataset is the most useful part of its API" - not useful part of API, simply - the most useful part of it

**Comment by abaranau** [comment]
"and use gauge and sum functions"

and use max and sum functions

**Comment by abaranau** [comment]
Example of the query in JSON format:
``` json
{
    "aggregation": "rack+server",
    "startTs": 1423370200,
    "endTs":   1423398198,
    "measurements": {"cpu.used": "MAX", "disk.reads": "SUM"},
    "resolution": 60,
    "dimensionValues": {"rack": "rack1"},
    "groupByDimensions": ["server"],
    "limit": 100
}
```

**Comment by abaranau** [comment]
Example response:

``` json
   [
    {
        "measureName": "disk.reads",
        "dimensionValues": {
            "server": "server1"
        },
        "timeValues": [
            {
                "timestamp": 1423370200,
                "value": 969
            },
            {
                "timestamp": 1423370260,
                "value": 360
            }
        ]
    },
    {
        "measureName": "disk.reads",
        "dimensionValues": {
            "server": "server2"
        },
        "timeValues": [
            {
                "timestamp": 1423370200,
                "value": 23
            },
            {
                "timestamp": 1423370260,
                "value": 444
            }
        ]
    },
    {
        "measureName": "cpu.used",
        "dimensionValues": {
            "server": "server1"
        },
        "timeValues": [
            {
                "timestamp": 1423370200,
                "value": 50
            },
            {
                "timestamp": 1423370260,
                "value": 55
            }
        ]
    },
    {
        "measureName": "cpu.used",
        "dimensionValues": {
            "server": "server2"
        },
        "timeValues": [
            {
                "timestamp": 1423370200,
                "value": 12
            },
            {
                "timestamp": 1423370260,
                "value": 56
            }
        ]
    }
]
```

**Comment by abaranau** [comment]
can we also link to cube guide somehow?

**Comment by abaranau** [comment]
Other than above comments, looks good!

**Comment by awholegunch** [comment]
I have implemented most of these comments, with the exception of the ones I didn't understand:

*"Querying data in Cube dataset is the most useful part of its API" - not useful part of API, simply - the most useful part of it"* -- not sure what you wanted here.

I will adjust the colors on the examples: I re-did them so they would fit...

**Comment by awholegunch** [comment]
Please take another look!

**Comment by abaranau** [comment]
I meant remove "api" word

**Comment by abaranau** [comment]
"Here's an example of configuring pre-aggregated view via dataset properties"

No pseudo sql words

**Comment by abaranau** [comment]
Just two minor nurse and merge!

**Pull request merged**
