### PR TITLE
Speed up unit-tests by using local MR instead of forking new processes

### PR DESCRIPTION
**Pull request by chtyim**
Tests get speed up from 300 seconds to 25 seconds.

### CODE REVIEW

**Comment by anew** [comment]
Where do you configure it to use local mode? Or is that the default if you don't start the mini cluster?

**Comment by chtyim** [comment]
Yup, that's the default.

**Comment by anew** [comment]
LGTM

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DUT3460-1

**Pull request merged**
