### PR TITLE
CDAP-1894 Delete Hive table partitions when PartitionedFileSet is truncated

### PR DESCRIPTION
**Pull request by ghelmling**

### CODE REVIEW

**Comment by prinam** [comment]
Build running here: http://builds.cask.co/browse/CDAP-RBT204-1

**Comment by albertshau** [comment]
:+1:

**Comment by anew** [comment]
LGTM

**Comment by chtyim** [comment]
Looks like the test was hanged (for over 10 mins not proceeding) and got killed by bamboo:

http://builds.cask.co/browse/CDAP-RBT204-1/log

**Comment by ghelmling** [comment]
Hung build was not due to my changes.  Second build passed: http://builds.cask.co/browse/CDAP-RBT204-2

**Pull request merged**
