### PR TITLE
[CDAP-3883] Fix ResourceCoordinatorTest testAssignment test is flaky

### PR DESCRIPTION
**Pull request by henry-cask**
Add longer timeout for blocking Queue for getting changes of resource partition tests.

### CODE REVIEW

**Comment by henry-cask** [comment]
Build:
http://builds.cask.co/browse/CDAP-RBT505-1

**Comment by henry-cask** [comment]
See https://github.com/caskdata/cdap/pull/4265 for review

**Comment by chtyim** [comment]
LGTM

**Comment by henry-cask** [comment]
Build passes ... merging

**Pull request merged**
