### PR TITLE
Release notes for CDAP v.2.8.3

### PR DESCRIPTION
**Pull request by anwar6953**
Quick build: http://builds.cask.co/browse/CDAP-DQBP39-2

### CODE REVIEW

**Comment by poornachandra** [comment]
LGTM

**Comment by awholegunch** [comment]
I made two commits—please check—otherwise, LGTM.

**Comment by anwar6953** [comment]
Lgtm

**Comment by anwar6953** [comment]
Quick build looks good; squashing and merging.

**Pull request merged**
