### PR TITLE
[CDAP-1639] app endpoint to return more details

### PR DESCRIPTION
**Pull request by anew**
[CDAP-1639](https://issues.cask.co/browse/CDAP-1639)

### CODE REVIEW

**Comment by anew** [comment]
Build running here http://builds.cask.co/browse/CDAP-DUT965-5

**Comment by sreevatsanraman** [comment]
lgtm :+1:

**Comment by anew** [comment]
@awholegunch I updated the documentation. Please take a quick look.

**Comment by anew** [comment]
waiting for build: http://builds.cask.co/browse/CDAP-DUT965-6

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Comment by anew** [comment]
The build finally passed. Merging now.

**Comment by awholegunch** [comment]
Docs: LGTM

**Pull request merged**
