### PR TITLE
CDAP-1652: Do not store unlimited number of versions in meta tables

### PR DESCRIPTION
**Pull request by abaranau**
https://issues.cask.co/browse/CDAP-1652

### CODE REVIEW

**Comment by abaranau** [comment]
http://builds.cask.co/browse/CDAP-DUT929-1

**Comment by chtyim** [comment]
LGTM

**Comment by ghelmling** [comment]
lgtm

**Comment by abaranau** [comment]
http://builds.cask.co/browse/CDAP-DUT929-2 GREEN

**Pull request merged**
