### PR TITLE
Removes socket closed event alert message. 

### PR DESCRIPTION
**Pull request by ajainarayanan**
Was causing js error and prevented from automatically refreshing browser when node server came up

### CODE REVIEW

**Comment by anwar6953** [comment]
Relevant JIRA:
https://issues.cask.co/browse/CDAP-4770

**Comment by anwar6953** [comment]
This works with Standalone dying, or just the node server dying and coming back up?

**Comment by anwar6953** [comment]
If it handles both cases - CDAP backend restarting as well as just Node server restarting - then LGTM!

**Comment by ajainarayanan** [comment]
@anwar6953 The initial change worked for independent scenarios. When backend goes down or node server goes down UI shows a message and will reconnect and load UI when either of them comes back. 

However when it happens in a sequence where when node server goes down and comes back up and then later after sometime when backend goes down UI didn't update to show that backend services are down. I have fixed this specific issue which should cover all scenarios I guess. I played around with different combination of failures and it worked as expected.

**Comment by elfenheart** [comment]
:+1: LGTM

**Comment by anwar6953** [comment]
LGTM!

**Pull request merged**
