### PR TITLE
Streams V3 API changes

### PR DESCRIPTION
**Pull request by sreevatsanraman**
PR contains the following changes
* Removed v3/namespaces/{id}/streams/{id}/info endpoint
* Added v3/namespaces/{id}/streams/{id} endpoint
* Removed v3/namespaces/{id}/streams/{id}/config endpoint
* Added v3/namespaces/{id}/streams/{id}/properties endpoint
* Corresponding Stream Client changes for CLI

Related JIRA: https://issues.cask.co/browse/CDAP-1641

Build: http://builds.cask.co/browse/CDAP-DUT936-2

### CODE REVIEW

**Comment by bdmogal** [comment]
:+1:

**Comment by anwar6953** [comment]
Can you file a JIRA to also make necessary updates to cdap-ingest repo?

**Comment by sreevatsanraman** [comment]
Good call @anwar6953 added https://issues.cask.co/browse/CDAP-1659

**Comment by sreevatsanraman** [comment]
Build passed, merging.

**Pull request merged**
