### PR TITLE
Doc Fixes

### PR DESCRIPTION
**Pull request by awholegunch**
This is a replacement for https://github.com/caskdata/cdap/pull/4137 which was closed last night. It addresses Sree's comment, and does the same thing as the other PR.

Adds the S3Avro and S3Parquet plugin documentation.
Fixes the CLI Help documentation (an earlier PR accidentally was to develop).
Standardizes various messages.
Simplifies the script that tests guarded ETL Java files.

Built at: http://builds.cask.co/browse/CDAP-DDB11-2

### CODE REVIEW

**Comment by albertshau** [comment]
lgtm

**Comment by awholegunch** [comment]
I just noticed that there are some files in release/3.2 related to this that shouldn't be there. Instead, they should have incorporated into this. I'll revise this PR and have it re-reviewed.

**Comment by awholegunch** [comment]
New build: http://builds.cask.co/browse/CDAP-DDB11-3

**Comment by albertshau** [comment]
lgtm

**Pull request merged**
