### PR TITLE
Move test files from app fabric src/main to src/test.

### PR DESCRIPTION
**Pull request by henry-cask**
Right now, there is a test directory in the cdap-app-fabric's src/main/java/.../cdap directory that primarily used for testing.

This PR is used to move it under src/test and make sure dependencies is using test-jar.

### CODE REVIEW

**Comment by chtyim** [comment]
LGTM

**Comment by henry-cask** [comment]
Build:
http://builds.cask.co/browse/CDAP-DUT1896-1

**Comment by henry-cask** [comment]
Thanks @chtyim ! Waiting the build to pass (hence the WIP ^_^)

**Comment by henry-cask** [comment]
Build passes

**Pull request merged**
