### PR TITLE
Added a FileContextLocationFactory that uses FileContext to perform Location operations

### PR DESCRIPTION
**Pull request by chtyim**
- Switch to use FileContextLocationFactory instead of HDFSLocationFactory

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
LGTM

**Comment by sreevatsanraman** [comment]
Please add the link for build in the PR and merge when the builds pass.

**Comment by chtyim** [comment]
Verified on secure cluster.

**Comment by chtyim** [comment]
Build running in http://builds.cask.co/browse/CDAP-RBT510-5

**Comment by chtyim** [comment]
Build passed. Squashing and merge.

**Pull request merged**
