### PR TITLE
modifies .btn-styles mixin to fix button state styling

### PR DESCRIPTION
**Pull request by astewes**
*  Modifies .btn-styles mixin to fix issue where \<button> elements were getting "stuck" in active/focus state
*  Adds correct default styling for .btn-default class

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@astewes Do we still need the system service detail view in admin to have styles to fix metadata/logs tab buttons?

**Comment by astewes** [comment]
@ajainarayanan i tried this out and yes, looks like the styles will need to be kept in admin. The default for the .active class is to darken the button color, but with Metadata/Logs, we want to override the default with a white background and use a box shadow to differentiate the active button.

**Comment by elfenheart** [comment]
@astewes @ajainarayanan added a small fix to this PR, fixing typo on workflow icon classname.

:+1: LGTM on @astewes changes

**Comment by ajainarayanan** [comment]
:+1: LGTM

**Pull request merged**
