### PR TITLE
Add notes about limitations on upgrade tools.

### PR DESCRIPTION
**Pull request by awholegunch**
Staged at:

- [Installation: Upgrade](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/admin-manual/installation/installation.html#upgrading-an-existing-version)
- [Release Notes](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/reference-manual/release-notes.html#new-features)
- [Stream Properties](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/reference-manual/http-restful-api/http-restful-api-v3/stream.html#setting-stream-properties)
- [Namespace Components](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/developers-manual/building-blocks/namespaces.html#namespace-components)
- [Namespace Editing](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/reference-manual/http-restful-api/http-restful-api-v3/namespace.html#http-restful-api-namespace-editing)
- [Resource Guarantees](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/admin-manual/operations/resource-guarantees.html)
- [Metrics Queries by Time Range](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/reference-manual/http-restful-api/http-restful-api-v3/metrics.html#querying-by-a-time-range)

### CODE REVIEW

**Comment by jwang47** [comment]
LGTM

**Comment by rohitsinha54** [comment]
LGTM

**Comment by awholegunch** [comment]
I have one more fix to add to this: fix for the Stream RESTful API.

**Comment by poornachandra** [comment]
Commit https://github.com/caskdata/cdap/commit/bcf0fbffa9524836d76fd32e4355dfef1da54a55 looks good.

**Comment by ajainarayanan** [comment]
Commits (https://github.com/caskdata/cdap/commit/26e79159bb3e83cb5008dd3b5bbf626e9d59398c) & (https://github.com/caskdata/cdap/commit/1c540d3c95cd53025f7abb19c046609bb95967ce) LGTM

**Comment by bdmogal** [comment]
781d8d5 LGTM

**Comment by bdmogal** [comment]
The namespace properties/scheduler.queue.name changes LGTM

**Comment by abaranau** [comment]
legitimate

**Pull request merged**
