### PR TITLE
removed validate stages/types in PipelineRegisterer 

### PR DESCRIPTION
**Pull request by gsps1**
we currently perform validation in linear way, has to be refactored after we introduced DAG in Transforms. 

currently we are disabling this and have a JIRA to refactor it later : 
https://issues.cask.co/browse/CDAP-4387

Build : http://builds.cask.co/browse/CDAP-DUT3288

### CODE REVIEW

**Comment by albertshau** [comment]
lgtm, though please change the commit message so that it starts with CDAP-4387.  That way the commit will automatically show up in the corresponding jira.

**Comment by gokulavasan** [comment]
Aren't there some unit tests that test the validation logic? That can be removed too? If there aren't then, then ok.

**Comment by gsps1** [comment]
@gokulavasan i have kept the validateTypes method which is used by tests, though its only used by tests.

**Comment by gokulavasan** [comment]
@gsps1 Sounds good

**Pull request merged**
