### PR TITLE
CDAP-5108 Refactor dataset admin service

### PR DESCRIPTION
**Pull request by poornachandra**
Build - http://builds.cask.co/browse/CDAP-DUT3664-1
Integration test - http://builds.cask.co/browse/CDAP-ITCC-145

### CODE REVIEW

**Comment by anew** [comment]
Before looking at the details, the new service seems to do the same thing as InMemoryDatsetOpExecutor, is that right?

**Comment by poornachandra** [comment]
InMemoryDatasetOpExecutor is a client side class. It uses RemoteDatasetFramework client to talk to DatasetAdminOpHTTPHandler, which is being re-factored in this PR.

**Comment by anew** [comment]
LGTM

**Comment by poornachandra** [comment]
Thanks for the review @anew. Build is green, merging.

**Pull request merged**
