### PR TITLE
Update pom for hbase-0.94 dependency

### PR DESCRIPTION
**Pull request by anwar6953**
Cherry-picking a commit that was merged against release/3.0:
https://github.com/caskdata/cdap/pull/4559

https://issues.cask.co/browse/CDAP-4368
http://builds.cask.co/browse/CDAP-RBTKEY281-1

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
LGTM

**Comment by anwar6953** [comment]
Currently trying to create a cluster from the feature branch.

**Comment by anwar6953** [comment]
The cluster I autobuilt from the feature branch had an issue similar to:
```
Exception in thread "main" java.lang.IllegalArgumentException: Not a host:port pair: PBUF
B
5release28-router-timeout4703-1000.dev.continuuity.net^P��^C^X<U+F3D7>��*^P^@
        at org.apache.hadoop.hbase.util.Addressing.parseHostname(Addressing.java:60)
        at org.apache.hadoop.hbase.ServerName.<init>(ServerName.java:101)
        at org.apache.hadoop.hbase.ServerName.parseVersionedServerName(ServerName.java:283)
        at org.apache.hadoop.hbase.MasterAddressTracker.bytesToServerName(MasterAddressTracker.java:77)
        at org.apache.hadoop.hbase.MasterAddressTracker.getMasterAddress(MasterAddressTracker.java:61)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:703)
        at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:126)
        at co.cask.cdap.data.runtime.main.MasterServiceMain.createSystemHBaseNamespace(MasterServiceMain.java:201)
        at co.cask.cdap.data.runtime.main.MasterServiceMain.init(MasterServiceMain.java:193)
        at co.cask.cdap.common.runtime.DaemonMain.doMain(DaemonMain.java:55)
        at co.cask.cdap.data.runtime.main.MasterServiceMain.main(MasterServiceMain.java:144)
2015-12-16 18:24:42,813 - INFO  [Thread-1:c.c.c.d.r.m.MasterServiceMain@288] - Stopping master.services
```
I hit this error again trying to autobuild from branch: hotfix/CDAP-3887-router-connection-timeout, and I suspect the error has to do with the changes in this PR.

**Comment by jwang47** [comment]
Right, this change causes the issue described in https://issues.cask.co/browse/CDAP-4468

**Pull request merged**
