### PR TITLE
Replace clearspring imports with Guava

### PR DESCRIPTION
**Pull request by ParthGandhi**

### CODE REVIEW

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by chtyim** [comment]
Do you know what brings in the clearspring dep? Can we exclude it?

**Comment by anwar6953** [comment]
I think its spark

**Comment by ParthGandhi** [comment]
Yeah, its `spark-core`. I don't know Spark well enough and didn't spend time trying to figure out if it actually gets used and whether excluding it is safe or not.

**Comment by ParthGandhi** [comment]
Build: http://builds.cask.co/browse/CDAP-DUT1174-1/

Merging this for now. Evaluating whether that dependency can be excluded is a bit more work and can be done separately.

**Pull request merged**
