### PR TITLE
add livereload for gulp

### PR DESCRIPTION
**Pull request by elfenheart**
Adding livereload back to gulp

### CODE REVIEW

**Comment by anwar6953** [comment]
Why do we check if its localhost?
If gulp is running also on a different host, shouldn't it also do then?

**Comment by anwar6953** [comment]
Btw whats the reason we remove it before release?

**Comment by elfenheart** [comment]
improving performance. That script is a deadweight on a production environment, adding a pub/sub events that is doing nothing.

**Comment by anwar6953** [comment]
Makes sense. Is there any way we can simply inject it if its built by gulp in development mode?
(That way we don't have to remove and bring it back every release/patch).

**Comment by elfenheart** [comment]
I believe we can do that, but let's do that in separate PR. Have to restructure the Gulp file, and have to dig through the build script.

**Comment by anwar6953** [comment]
Ok, this LGTM

**Pull request merged**
