### PR TITLE
Hotfix/remove pref cli

### PR DESCRIPTION
**Pull request by gokulavasan**
Hide Preferences CLI and ignore Preferences' CLITest.

Bamboo : https://builds.cask.co/browse/CDAP-RBT103-1

### CODE REVIEW

**Comment by bdmogal** [comment]
Why do we have to ignore the unit test? That can keep running, no? Otherwise LGTM :+1:

**Comment by gokulavasan** [comment]
@bdmogal If the pref commands are commented out, wouldn't CLIMainTest fail. Also I saw that the namespace tests were commented out too in the CLIMainTest.

**Comment by bdmogal** [comment]
Makes sense. We should probably then just have a disable functionality for commands we do not want to expose. For a later PR though. :+1:

**Comment by gokulavasan** [comment]
Build passed. Merging.

**Pull request merged**
