### PR TITLE
Upgrade to Java7

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by chtyim** [comment]
Build is green with Java7. http://builds.cask.co/browse/CDAP-RJ7

**Comment by bdmogal** [comment]
This would not work with Java 6 anymore, right? Or did I miss something?

**Comment by chtyim** [comment]
It would not. Refer to https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cdap-user/cjTsfAXo3oE/52ShCpu4LFkJ

**Comment by bdmogal** [comment]
Oh cool. so we made that call. :+1:

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Pull request merged**
