### PR TITLE
Spark Refactor using Controller As

### PR DESCRIPTION
**Pull request by elfenheart**
Refactor Spark programs to use Controller As syntax.

Cannot test Spark in Cluster. Need to pull locally.

### CODE REVIEW

**Comment by ajainarayanan** [comment]
:+1: LGTM. Any specific reason why we are hiding everything in the status page until the spark program is run atleast once? The other programs shows a default status view with/without a run.

**Comment by ajainarayanan** [comment]
Also wondering if we need to be consistent with the changes made in this PR (https://github.com/caskdata/cdap/pull/3047) Pulled it locally and it seemed to work fine. Could we figure out if we need those changes or is that PR invalid (as in the runs dropdown works just fine when we navigate between states?)

**Comment by elfenheart** [comment]
Updated PR to be consistent with #3047

**Comment by ajainarayanan** [comment]
:+1: LGTM

**Pull request merged**
