### PR TITLE
Exclude asm from jersey-servlet

### PR DESCRIPTION
**Pull request by poornachandra**
Currently when running tests of an CDAP application, the following exception is thrown -
```
test(co.cask.tracker.TrackerAppTest)  Time elapsed: 0.08 sec  <<< ERROR!
java.lang.IncompatibleClassChangeError: class org.apache.twill.internal.utils.Dependencies$DependencyClassVisitor has interface org.objectweb.asm.ClassVisitor as super class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.twill.internal.utils.Dependencies.findClassDependencies(Dependencies.java:86)
        at co.cask.cdap.common.lang.ProgramResources.findClassDependencies(ProgramResources.java:289)
        at co.cask.cdap.common.lang.ProgramResources.createBaseResources(ProgramResources.java:155)
        at co.cask.cdap.common.lang.ProgramResources.getBaseResources(ProgramResources.java:132)
        at co.cask.cdap.common.lang.ProgramResources.createVisibleResources(ProgramResources.java:115)
        at co.cask.cdap.common.lang.ProgramResources.getVisibleResources(ProgramResources.java:105)
        at co.cask.cdap.internal.test.AppJarHelper.createDeploymentJar(AppJarHelper.java:52)
        at co.cask.cdap.internal.test.AppJarHelper.createDeploymentJar(AppJarHelper.java:127)
        at co.cask.cdap.internal.AppFabricClient.deployApplication(AppFabricClient.java:360)
        at co.cask.cdap.test.UnitTestManager.deployApplication(UnitTestManager.java:157)
        at co.cask.cdap.test.TestBase.deployApplication(TestBase.java:409)
        at co.cask.cdap.test.TestBase.deployApplication(TestBase.java:403)
        at co.cask.cdap.test.TestBase.deployApplication(TestBase.java:424)
        at co.cask.tracker.TrackerAppTest.test(TrackerAppTest.java:50)
```

Build - http://builds.cask.co/browse/CDAP-DUT3617-2

### CODE REVIEW

**Comment by bdmogal** [comment]
How come we didn't catch this earlier? Was this introduced by a recent change?

**Comment by poornachandra** [comment]
Not sure why we didn't catch it. When @russorat tried running tests for Tracker app he got this exception. This was introduced by PR https://github.com/caskdata/cdap/pull/5030.

**Comment by bdmogal** [comment]
Hmmm, strange that it was introduced in ``release/3.3``, but none of our tests caught it. Perhaps backport it to ``release/3.3`` too?

The code change LGTM!

**Comment by sreevatsanraman** [comment]
There is one more asm dependency. Will this cause an issue

```
 +- co.cask.cdap:cdap-app-fabric:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- co.cask.cdap:cdap-notifications:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- co.cask.cdap:cdap-authorization-dataset-plugin:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- org.quartz-scheduler:quartz:jar:2.2.0:compile
[INFO] |  |  \- c3p0:c3p0:jar:0.9.1.1:compile
[INFO] |  +- org.quartz-scheduler:quartz-jobs:jar:2.2.0:compile
[INFO] |  +- com.ning:async-http-client:jar:1.7.18:compile
[INFO] |  +- io.netty:netty:jar:3.6.6.Final:compile
[INFO] |  +- org.apache.hadoop:hadoop-mapreduce-client-common:jar:2.3.0:compile
[INFO] |  |  \- org.apache.hadoop:hadoop-yarn-server-common:jar:2.3.0:compile
[INFO] |  +- org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:2.3.0:compile
[INFO] |  |  \- com.google.inject.extensions:guice-servlet:jar:3.0:compile
[INFO] |  +- org.apache.hadoop:hadoop-mapreduce-client-app:jar:2.3.0:compile
[INFO] |  +- org.apache.hbase:hbase-common:jar:0.98.6.1-hadoop2:compile
[INFO] |  +- org.apache.commons:commons-compress:jar:1.9:compile
[INFO] |  \- org.apache.hive:hive-service:jar:1.1.0:compile
[INFO] |     +- org.apache.hive:hive-metastore:jar:1.1.0:compile
[INFO] |     |  +- org.apache.hive:hive-serde:jar:1.1.0:compile
[INFO] |     |  |  +- org.apache.hive:hive-common:jar:1.1.0:compile
[INFO] |     |  |  |  +- log4j:apache-log4j-extras:jar:1.2.17:compile
[INFO] |     |  |  |  \- org.apache.ant:ant:jar:1.9.1:compile
[INFO] |     |  |  |     \- org.apache.ant:ant-launcher:jar:1.9.1:compile
[INFO] |     |  |  +- net.sf.opencsv:opencsv:jar:2.3:compile
[INFO] |     |  |  \- com.twitter:parquet-hadoop-bundle:jar:1.6.0rc3:compile
[INFO] |     |  +- org.apache.hive:hive-shims:jar:1.1.0:compile
[INFO] |     |  |  +- org.apache.hive.shims:hive-shims-common:jar:1.1.0:compile
[INFO] |     |  |  +- org.apache.hive.shims:hive-shims-0.20S:jar:1.1.0:runtime
[INFO] |     |  |  +- org.apache.hive.shims:hive-shims-0.23:jar:1.1.0:runtime
[INFO] |     |  |  |  \- org.apache.hadoop:hadoop-yarn-server-resourcemanager:jar:2.6.0:runtime
[INFO] |     |  |  |     +- com.sun.jersey:jersey-json:jar:1.9:runtime
[INFO] |     |  |  |     |  +- com.sun.xml.bind:jaxb-impl:jar:2.2.3-1:runtime
[INFO] |     |  |  |     |  +- org.codehaus.jackson:jackson-jaxrs:jar:1.8.3:runtime
[INFO] |     |  |  |     |  \- org.codehaus.jackson:jackson-xc:jar:1.8.3:runtime
[INFO] |     |  |  |     +- com.sun.jersey.contribs:jersey-guice:jar:1.9:runtime
[INFO] |     |  |  |     |  \- com.sun.jersey:jersey-server:jar:1.9:runtime
[INFO] |     |  |  |     |     \- asm:asm:jar:3.1:runtime

```

**Comment by poornachandra** [comment]
Strange I don't see it on my branch. Which branch are you using, and what command are you running?
```
$ mvn package dependency:tree -DskipTests | grep asm
[INFO] +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO] |  |  +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO]    +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-all:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-all:jar:5.0.3:compile
```

**Comment by poornachandra** [comment]
@bdmogal Once this PR is reviewed, I'll close this PR and open another against 3.3 branch.

**Comment by poornachandra** [comment]
Discussed offline with @sreevatsanraman, he used `mvn dependency:tree -DskipTests` which lists runtime dependencies also. In his case, asm-3.1 is getting pulled in by `org.apache.hadoop:hadoop-yarn-server-resourcemanager:jar:2.6.0:runtime`. Since resource manager jar would only get included in distributed mode, and we use classloader isolation in distributed version, this runtime dependency should not cause any issue.

**Comment by poornachandra** [comment]
Build is green, will close this PR and open against 3.3 branch

**Pull request closed without merging**
