### PR TITLE
Preparing for 2.6.2 release

### PR DESCRIPTION
**Pull request by poornachandra**

### CODE REVIEW

**Comment by poornachandra** [comment]
http://builds.cask.co/browse/CDAP-DUT1087-1

**Comment by sreevatsanraman** [comment]
Some files are missing the update 
`
[sree@mac cdap (feature/prepare-2.6.2)]$ find . -name 'pom.xml' | xargs grep 2.6.1
./cdap-archetypes/cdap-app-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>2.6.1</cdap.version>
./cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>2.6.1</cdap.version>
./cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>2.6.1</cdap.version>
./cdap-examples/SparkKMeans/pom.xml:    <cdap.version>2.6.1</cdap.version>
./cdap-examples/SparkPageRank/pom.xml:    <cdap.version>2.6.1</cdap.version>
`

**Comment by poornachandra** [comment]
SparkKMeans and SparkPageRank poms are updated. I'll update the archetypes poms.

**Comment by poornachandra** [comment]
@sreevatsanraman Actually archetypes poms are also updated, can you please verify again?

**Comment by poornachandra** [comment]
@sreevatsanraman Good catch. Fixed in all places. Please take a look.

**Comment by sreevatsanraman** [comment]
lgtm :+1:

**Pull request merged**
