### PR TITLE
Move stream CLI commands to INGEST category

### PR DESCRIPTION
**Pull request by jwang47**

### CODE REVIEW

**Comment by awholegunch** [comment]
I'd like to change some of these help messages, but there's no point as they are also in the code and unless we change them there, they will get wiped out the next update. Was there a PR to update the source?

**Comment by jwang47** [comment]
This PR just moves stream commands to the ingest category and copy pastes the output from `GenerateCLIDocsTable`. We can modify the help messages in a separate PR.

**Comment by awholegunch** [comment]
ok, thanks.

**Comment by awholegunch** [comment]
LGTM.

**Pull request merged**
