### PR TITLE
CDAP-5845 Do not package spark-core with examples

### PR DESCRIPTION
**Pull request by rohitsinha54**
Issue : https://issues.cask.co/browse/CDAP-5845

Working on testing it.

### CODE REVIEW

**Comment by chtyim** [comment]
LGTM

**Comment by gokulavasan** [comment]
I noticed a redundant guava dependency in SpamClassifier example. Can you remove that as well?

**Comment by rohitsinha54** [comment]
Build http://builds.cask.co/browse/CDAP-DUT4077-1

**Comment by bdmogal** [comment]
why not also mark these ``provided`` in the ``dependencyManagement`` in the parent pom?

**Comment by rohitsinha54** [comment]
I talked to Terence we want all examples to provide their scope.

**Pull request merged**
