### PR TITLE
Make sure the fork executor terminates before the Workflow completed

### PR DESCRIPTION
**Pull request by chtyim**
- This is needed since the individual program run records is written
  from the thread inside the executor.

### CODE REVIEW

**Comment by sagarkapare** [comment]
LGTM :+1:

**Comment by chtyim** [comment]
Building in http://builds.cask.co/browse/CDAP-RBT470-1

**Comment by chtyim** [comment]
Verified on cluster.

**Comment by bdmogal** [comment]
Build is green. Merging.

**Comment by sagarkapare** [comment]
Verified for the positive(normal) test case as well.

**Pull request merged**
