### PR TITLE
CDAP-4320: TestFrameworkTestRun.testAppWithServices is flaky

### PR DESCRIPTION
**Pull request by jwang47**
- Service calls will occasionally fail with 500 response code,
  so retry service calls a few times before failing the test

### CODE REVIEW

**Comment by jwang47** [comment]
https://issues.cask.co/browse/CDAP-4320
http://builds.cask.co/browse/CDAP-RBT540

**Comment by anew** [comment]
@jwang47 please provide a description of what the problem was and how it was fixed.

**Comment by jwang47** [comment]
@anew Added.

**Comment by anew** [comment]
why do the service calls fail? Seems like that is the root cause of the failure and that should be fixed instead.

**Comment by jwang47** [comment]
Haven't looked much into that yet, since I wasn't able to reproduce and the logs are gone now.

**Comment by anew** [comment]
Looking at that service handler, the only way it can fail is:

a) read from HBase fails
b) HBase returns null and hence sendJson() throws NPE. 

I think b) is a lot more likely, as there can be a race condition between that the worker writes the value and the get request for that value is made.

**Comment by sreevatsanraman** [comment]
@jwang47  let's not put a bandaid fix. let's fix the root cause.

**Pull request closed without merging**
