### PR TITLE
Fix CubeQuery Javadoc.

### PR DESCRIPTION
**Pull request by awholegunch**
Fixes broken Javadocs by surrounding code sample in \<code> and \</code> in addition to \<pre> and \</pre>.

The problem can be seen in the currently staged javadocs: [CubeQuery](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT/en/reference-manual/javadocs/co/cask/cdap/api/dataset/lib/cube/CubeQuery.html)

### CODE REVIEW

**Comment by abaranau** [comment]
After change:

screen shot 2015-05-01 at 11 12 53 am

**Comment by abaranau** [comment]
BEfore change it was good. Are you sure we need the change?

**Comment by awholegunch** [comment]
It breaks the Javadoc build. Look at this link: [CubeQuery](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT/en/reference-manual/javadocs/co/cask/cdap/api/dataset/lib/cube/CubeQuery.html). Let me see if I can get it to work with both.

**Comment by abaranau** [comment]
LGTM

**Pull request merged**
