### PR TITLE
(CDAP-3627) Update examples and docs to use HttpContentConsumer

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by awholegunch** [comment]
Quick Build is running: [build results](http://builds.cask.co/browse/CDAP-DOB11-1)

**Comment by chtyim** [comment]
Doc build passed: http://builds.cask.co/browse/CDAP-DOB11

**Comment by awholegunch** [comment]
LGTM.

**Comment by chtyim** [comment]
This PR also addressed @anew comments about the example classes in https://github.com/caskdata/cdap/pull/4249

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DUT2913

**Comment by chtyim** [comment]
Squashed commits.

**Pull request merged**
