### PR TITLE
fix the adapter directory for standalone.

### PR DESCRIPTION
**Pull request by albertshau**

### CODE REVIEW

**Comment by anwar6953** [comment]
Moving plugins up one level because /data is supposed to be untouched externally? Or whats the reason?

**Comment by chtyim** [comment]
I think it's because:

1. `data` directory is for user and system data, hence a unrecoverable reset for SDK is to simply delete that directory and we don't want that to delete the adapter jar as well.
2. The SDK build has the adapter jar stores in `$SDK_HOME/plugins`, not `$SDK_HOME/data/plugins`.

**Comment by chtyim** [comment]
Change LGTM.

**Comment by albertshau** [comment]
yep what trex said

**Pull request merged**
