### PR TITLE
Remove unnecessary InMemoryBusinessMetadataStore

### PR DESCRIPTION
**Pull request by henry-cask**
The new InMemoryBusinessDatastore was added in-rush to fix guice error. 
The awesome thing is that looks like using the DefaultBusinessMetadataStore work fine.

### CODE REVIEW

**Comment by henry-cask** [comment]
@bdmogal @poornachandra for review

**Comment by henry-cask** [comment]
Build: 
http://builds.cask.co/browse/CDAP-RBT434-1

**Comment by bdmogal** [comment]
:+1: Merge after successful build.

**Comment by henry-cask** [comment]
Build passes, merging ...

**Pull request merged**
