### PR TITLE
Fix MapReduceTaskContextProvider in distributed mode

### PR DESCRIPTION
**Pull request by chtyim**
- On the MR client side (MapReduceRuntimeService) in distributed mode
  use the provide with the same system injector

### CODE REVIEW

**Comment by sagarkapare** [comment]
LGTM :+1:

**Comment by chtyim** [comment]
Verified on cluster.

**Comment by chtyim** [comment]
Building in http://builds.cask.co/browse/CDAP-RBT467-1

**Comment by chtyim** [comment]
Build passed.

**Pull request merged**
