### PR TITLE
Feature/ui truncate v2 api

### PR DESCRIPTION
**Pull request by elfenheart**
Change V2 APIs to V3

### CODE REVIEW

**Comment by ajainarayanan** [comment]
:+1: LGTM

**Comment by anwar6953** [comment]
This seems very similar to what we have in widget.js (the time series controller).
Should this be reusing the same code there?

Either way, this doesn't seem like it would work, because it is not interpolating the metric values with zeros. (I'm not sure what the chart would look like).

**Comment by elfenheart** [comment]
Changing operation28 to dashboard in separate PR

**Comment by anwar6953** [comment]
Ok, using widgets (the whole operation28 doesn't need to be a dashboard though) would help centralize the logic.

**Pull request merged**
