### PR TITLE
CDAP-5048 Add doc support for Google Tag Manager

### PR DESCRIPTION
**Pull request by awholegunch**
Add new Google Tag Manager code support, and remove old Google Analytics.
Removes some blank lines in the layout template that were making the header extra long.
Corrected formatting of the Amazon SQS comment tags.

Fix for https://issues.cask.co/browse/CDAP-5048.

Passes [Quick Build 4](http://builds.cask.co/browse/CDAP-DOB127-4).

You can see the results by looking at the source of [any of the pages](http://builds.cask.co/artifact/CDAP-DOB127/shared/build-4/Docs-HTML/3.3.2-SNAPSHOT/en/index.html).

### CODE REVIEW

**Comment by russorat** [comment]
LGTM
fullscreen_2_24_16__9_47_pm

**Comment by awholegunch** [comment]
I've kicked off a Docs Develop Build (http://builds.cask.co/browse/CDAP-DDB33-1). This will build (but not deploy) both GitHub and Web versions, so we can check that the correct code has been included in each.

**Comment by anwar6953** [comment]
Can this go into develop branch instead?
If its not needed in 3.3.2 (which is more sort of a bugfix release, due to critical issue found), then it should go to 3.4, right?

**Comment by russorat** [comment]
I chatted with @sreevatsanraman yesterday and if possible, it would be great to get this into the 3.3.2 release. This change allows us to get a much better view of how much web traffic our site is getting and we have already migrated the main cask.co site and blog to use this.

**Comment by anwar6953** [comment]
Got it.
:+1:

**Comment by awholegunch** [comment]
I download the GitHub version from the last build, and it has the correct tag embedded in it.

**Pull request merged**
