### PR TITLE
Disallow widget creation, if user specifies uneven number of parts fo…

### PR DESCRIPTION
**Pull request by anwar6953**
…r the metrics context

This is in response to the FIXME from:
https://github.com/caskdata/cdap/commit/86efa3b6d40c8d220486d889031c1fd28c1758a9

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@anwar6953 Technically I can still type in a context (app.ETLBatch.something.something or just app.ETLBatch.. ) and it would let me add the widget. But technically it wouldn't add any widget right? Would we even want the user to type in the context/metrics textboxes? If yes should we validate whatever they have typed is a valid context/metric?

**Comment by anwar6953** [comment]
@ajainarayanan This disallows the user from creating the widget (the green submit button is disabled), if this validation returns false.

**Comment by ajainarayanan** [comment]
@anwar6953 ok. Can we then add a TODO to add a check for valid context and to alert the user that widget is not created because of wrong context. 

Also if we are disabling the add button for odd #of contexts then can we remove the throwing error in the query-helper.js utility function?

**Comment by ajainarayanan** [comment]
If for minor comments :+1: LGTM

**Comment by anwar6953** [comment]
I added the TODO. I think we can leave the error checking in query-helper.js in place, in case that utility method is incorrectly used from elsewhere also (from flow page or overview page, etc).

**Pull request merged**
