### PR TITLE
Feature/ui styling hydrator dyanmic bottompanel

### PR DESCRIPTION
**Pull request by astewes**
*  Adds minimize and maximize buttons to bottom panel header
*  Bottom panel is now collapsed by default
*  Adds functionality to clear/reset errors each time a top panel action (i.e., Validate, Publish) is triggered
*  Node Config tab: Removes Save and Reset buttons
*  Console tab: Adds error count badge to console tab
*  Console tab: Adds flashing background color indicator based on error type

**cluster name**: *hydrator-bottompanel*

### CODE REVIEW

**Comment by nitinmotgi** [comment]
What's stopping this from being merged ? @ajainarayanan @sreevatsanraman @astewes

**Comment by astewes** [comment]
@nitinmotgi it should be ready to merge, but @ajainarayanan was going to do a final review to ensure nothing was overlooked.

**Comment by ajainarayanan** [comment]
:+1: Looks awesome!

One minor caveat. When the bottom panel is minized and if we add more #of nodes such that it goes beyond the collapsed bottom panel we are not able to scroll down fully to the see the last node. Apart from that it looks absolutely :smiley: :fireworks: 

collapsablebottompanel

**Comment by ajainarayanan** [comment]
:+1: LGTM

**Pull request merged**
