### PR TITLE
Merge 3.2.1 doc fixes to develop

### PR DESCRIPTION
**Pull request by awholegunch**
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB8-2)

Cherry-picks changes in release/3.2 in order to fix the develop branch doc build.

### CODE REVIEW

**Comment by anwar6953** [comment]
Why not merge the entire release branch into develop?

**Comment by awholegunch** [comment]
Because I didn't want to handle fixing any conflicts?....which, it looks like I have anyways!

**Comment by anwar6953** [comment]
Ah yeah, release branch was recently released into develop.
I don't think this PR is necessary any longer.

**Comment by awholegunch** [comment]
No longer needed.

**Pull request closed without merging**
