### PR TITLE
Cleanup of QueueAdmin interface

### PR DESCRIPTION
**Pull request by chtyim**
- QueueAdmin should always take QueueName instead of String to operate on

### CODE REVIEW

**Comment by albertshau** [comment]
lgtm, but there are conflicts

**Comment by chtyim** [comment]
Damn... Ali merged before me.

**Comment by chtyim** [comment]
Conflict resolved.

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DUT1030-3

**Pull request merged**
