### PR TITLE
(CDAP-5085) Update CDAP to use the new Spark API

### PR DESCRIPTION
**Pull request by chtyim**
- Small enhancement to the Spark API
  - Make StreamEvent serializable
- Modify all examples and unit-tests
- Moved Spark related unit-test to cdap-app-fabric-tests, cdap-unit-test or cdap-cli-tests modules
- Updated ETLSpark to use the new Spark API
  - Redefined the Spark plugin API to follow the new Spark API

### CODE REVIEW

**Comment by chtyim** [comment]
Again. This PR is merging to the CDAP-5085-Staging branch. The core changes has been reviewed in https://github.com/caskdata/cdap/pull/5457

**Comment by anew** [comment]
Since this has been reviewed already: LGTM

**Comment by anew** [comment]
Uh wait, I think I misunderstood.

**Comment by poornachandra** [comment]
Since most of the changes are for test cases (other than ETL Spark context changes), LGTM if all tests pass.

**Comment by chtyim** [comment]
Waiting for test. http://builds.cask.co/browse/CDAP-DUT3884-2

**Comment by chtyim** [comment]
New build after fixing NPE in unit-test:

http://builds.cask.co/browse/CDAP-DUT3884

**Comment by poornachandra** [comment]
LGTM

**Comment by chtyim** [comment]
Only one flaky test failed. Merge it and run the test on release again.

**Pull request merged**
