### PR TITLE
Using runid time range to limit log retrival

### PR DESCRIPTION
**Pull request by poornachandra**
JIRA - https://issues.cask.co/browse/CDAP-2053

### CODE REVIEW

**Comment by poornachandra** [comment]
Build - http://builds.cask.co/browse/CDAP-RBT220-1

**Comment by sreevatsanraman** [comment]
LGTM :-1:

**Comment by poornachandra** [comment]
Build - http://builds.cask.co/browse/CDAP-RBT220-3

**Comment by sreevatsanraman** [comment]
Build passed. Merging.

**Pull request merged**
