### PR TITLE
CDAP-3386 Fix for running Spark through Workflow on HDP2.2 by adding …

### PR DESCRIPTION
**Pull request by sagarkapare**
…spark classes in the classpath

### CODE REVIEW

**Comment by sagarkapare** [comment]
JIRA: https://issues.cask.co/browse/CDAP-3386

**Comment by sagarkapare** [comment]
Verified on the HDP 2.2 and Spark program executed correctly through the Workflow. 
@chtyim Please review. Thanks!

**Comment by bdmogal** [comment]
LGTM

**Comment by chtyim** [comment]
Merge it.

**Pull request merged**
