### PR TITLE
(CDAP-3145) Fix a bug in ResourceCoordinator.

### PR DESCRIPTION
**Pull request by chtyim**
- Instead of using the old set of discoverables in performAssignment, always use the live ServiceDiscovered to get the latest sets of discoverables
- This fixes the case where the coordinator needs to fetch the old assignment while the set is empty, followed by an update in the set of discoverables to become non-empty.

### CODE REVIEW

**Comment by chtyim** [comment]
Verified on cluster. Step to verify is to kill the metrics processor container multiple times to see if the correct assignment can be restored after the leader for resource coordinator is up.

**Comment by chtyim** [comment]
Build: http://builds.cask.co/browse/CDAP-RBT391-1

**Comment by gsps1** [comment]
where/how does the coordinator fetches old assignment when the set is empty ?

**Comment by abaranau** [comment]
looks good from first look, will ask couple Qs in a min at office ;)

**Comment by abaranau** [comment]
we talked. LGTM

**Comment by chtyim** [comment]
Build passed. Merging.

**Pull request merged**
