### PR TITLE
Revert "(CDAP-4777) Remove the inaccurate error log from flowlet on s…

### PR DESCRIPTION
**Pull request by chtyim**
…tart if there is stream event triggering the property change listener."

This reverts commit 77582204578e6894b023ddfcd67858ce1856db65.

### CODE REVIEW

**Comment by gokulavasan** [comment]
LGTM 👍

**Comment by anwar6953** [comment]
Relevant JIRA: https://issues.cask.co/browse/CDAP-5810

**Comment by chtyim** [comment]
Verified on the cluster.

**Comment by chtyim** [comment]
Build: http://builds.cask.co/browse/CDAP-DUT4075

**Comment by sreevatsanraman** [comment]
Build passed. Merging.

**Comment by chtyim** [comment]
Build passed.

**Pull request merged**
