### PR TITLE
Feature/ui styling system health

### PR DESCRIPTION
**Pull request by astewes**

### CODE REVIEW

**Comment by elfenheart** [comment]
:+1: LGTM

**Comment by elfenheart** [comment]
screen shot 2015-04-22 at 6 09 08 pm

Don't we want the charts to be pulled right?

**Comment by bdmogal** [comment]
Yea, to the right would be good.

**Comment by nitinmotgi** [comment]
- Edges for count indicator curved : border-radius: 4px
- Increase font weight a little bit
- Move to right, gap same as what's with green light.

**Comment by nitinmotgi** [comment]
LGTM :+1:

**Pull request merged**
