### PR TITLE
(CDAP-20) Removed guava dependency from cdap-api

### PR DESCRIPTION
**Pull request by chtyim**
- Copy and modify the guava TypeToken class
  - Copy guava classes needed by the TypeToken class
  - Restrict copying all dependent classes by:
    - Removing usage on Immutable collections
    - Partially copy certain core guava classes
- Added missing guava dependencies that used to come from
  cdap-api transitively

This is the final PR for removing guava from cdap-api.
Also, please don't comment on the style/code/comment in the copied guava classes.

### CODE REVIEW

**Comment by albertshau** [comment]
lgtm

**Comment by nitinmotgi** [comment]
Should copyright be preserved ? We made a copy so it shouldn't be our copyright ?

**Comment by chtyim** [comment]
We copy and modify, how do we handle copy right in this case?

**Comment by chtyim** [comment]
Checked the Apache license. I retained the original Guava copyright (for classes that are copied) as well as adding our own.

**Comment by chtyim** [comment]
Build passed. http://builds.cask.co/browse/CDAP-DUT3618-9

**Comment by awholegunch** [comment]
Copyright text LGTM.

**Comment by chtyim** [comment]
Squashed.

**Pull request merged**
