### PR TITLE
(CDAP-3735) Make sure RecordWriter in MultipleOutputs are closed.

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by chtyim** [comment]
Building in http://builds.cask.co/browse/CDAP-RBT476-1

**Comment by sagarkapare** [comment]
LGTM

**Comment by chtyim** [comment]
Building in http://builds.cask.co/browse/CDAP-RBT476-3

**Comment by anwar6953** [comment]
LGTM

**Comment by anwar6953** [comment]
Note: they were being closed before this PR also, but too late.

I think they need to be closed before OutputCommitter#commitTask, which wasn't happening before.

**Pull request merged**
