### PR TITLE
show default ns upon cli startup

### PR DESCRIPTION
**Pull request by anwar6953**
Helps resolve: https://issues.cask.co/browse/CDAP-1517
Build: http://builds.cask.co/browse/CDAP-DUT860-1

### CODE REVIEW

**Comment by albertshau** [comment]
:+1:

**Comment by ParthGandhi** [comment]
:+1:

**Comment by bdmogal** [comment]
Only one question - what happens when there are no namespaces in the system? I think this will show the prompt correctly, but it really may not exist, no? what if someone does a ``describe namespace default`` after seeing this prompt? Not something that needs to be fixed in this PR, but wondering.

**Comment by anwar6953** [comment]
well, definitely, the CLI startup would have to be redesigned if the default namespace doesn't exist by default.

**Comment by bdmogal** [comment]
I like a fix that @nitinmotgi suggested earlier. When you request for all namespaces, if size is zero, create default namespace then list. 
similarly when you do a get, create it as well.

**Comment by anwar6953** [comment]
yea that seems like a fair solution.
Not just if list is size 0, but if list !contains default ns, right?
For instance, someone could start cdap instance, create 'foo' namespace, and then do a listNamespaces call.

**Comment by bdmogal** [comment]
Yup.

**Comment by bdmogal** [comment]
I don't know whether you want to wait on this PR though. This will just show that you are in the default namespace, when there may not be such a namespace. guess we could do it separately.

**Comment by anwar6953** [comment]
yea i wont wait on that.

**Pull request merged**
