### PR TITLE
Update cdap-defaults.xml

### PR DESCRIPTION
**Pull request by awholegunch**
Added a Metadata Configuration section, and placed it in the correct location.

Update the Security Configuration section to match recent changes in the docs.

### CODE REVIEW

**Comment by bdmogal** [comment]
@awholegunch can you put this on-hold until https://github.com/caskdata/cdap/pull/3961 is merged? Its adding another param, and is very close to merging.

**Comment by bdmogal** [comment]
The contents look good, but will have to be updated after #3961

**Comment by awholegunch** [comment]
On-hold until #3961 ; added guarding of the cdap-default.xml. Will need one additional commit to pick up the final MD5 hash.

**Comment by awholegunch** [comment]
Kicking off build...

**Comment by bdmogal** [comment]
@awholegunch, this will need an update post #3997 as well.

**Comment by bdmogal** [comment]
@awholegunch all blocking PRs for this one have been merged. The metadata changes in this PR LGTM.

**Comment by bdmogal** [comment]
LGTM

**Pull request merged**
