### PR TITLE
Move kafka.seed.brokers

### PR DESCRIPTION
**Pull request by awholegunch**
The kafka.seed.brokers property, in the cdap-default.xml file, was in the wrong section of the file. This caused the property to be in the wrong section of the documentation's table describing the contents of the file. This PR fixes that.

### CODE REVIEW

**Comment by dereklwood** [comment]
:+1: lgtm

**Comment by bdmogal** [comment]
@awholegunch why is this the wrong section? The property is used in the CDAP Log System, so it seems right that it is in the logging section?

**Comment by awholegunch** [comment]
Well, Derek would know more, but if you are configuring CDAP, would you not expect that the place for the kafka.seed.brokers would be in the Kafka section? If you look at the [section for Kafka Server](http://docs.cask.co/cdap/3.3.0-SNAPSHOT/en/admin-manual/installation/cdap-site.html#kafka-server), it looks odd that the first item of [the Logging section](http://docs.cask.co/cdap/3.3.0-SNAPSHOT/en/admin-manual/installation/cdap-site.html#logging) is "kafka.seed.brokers"...take a look at this and let me know what you think. I'm thinking of it from a configuration and setup point of view, and where someone would look for this property...

**Comment by bdmogal** [comment]
Maybe we need to name this property better, but that's never an easy thing to do considering backward compatibility, deprecation etc. However, kafka-server does not seem like the right place for it, because it is used in the log saver (to know where kafka is running), and not in the kafka-server (which defines the server side properties). @poornachandra @dereklwood correct me if I'm wrong.

**Comment by awholegunch** [comment]
Given that info, we could add that to the description, and then that would explain why it was in the Logging Section. But can other services use that setting also?

**Comment by dereklwood** [comment]
My thoughts are that a typical user should just see CDAP as a black box and shouldn't need to know which component talks to what.  In that sense, if I change something kafka-related like adding a new server, then I should just need to look in the kafka section.

But we are also not consistent with this.  router.server.address and router.server.port are used by UI to connect to router.  router.server.address is in the UI section, while router.server.port is in the Router section.  We need to be consistent whatever we decide.

But I would vote for putting kafka.seed.brokers in the kafka section and router.server.[address,port] in the router section because 1) I think it's easier for the new user and 2) if we add another client that uses these same settings then how would we categorize it?

**Comment by awholegunch** [comment]
@bdmogal What do you think of @dereklwood suggestions?

**Comment by poornachandra** [comment]
I think ideal solution would be to have both forward and reverse lookups. 

We can have all configuration parameters organized by components, so that when someone wants to setup a particular component they know what parameters affect the component. 

We also need a kind of indexed (reverse) lookup for cases like - Kafka server hostname changes, then we need to identify all parameters that need to be updated to propagate the change.

**Comment by awholegunch** [comment]
I think I asked this before, but I think we **cannot** add more fields to that file, as it is a quasi-standard Hadoop file, right? Otherwise, we could add tags and then mark each property as to the components involved…

**Comment by poornachandra** [comment]
There is a JIRA open to have the cdap configuration parameters in a different format from which other configuration files like cdap-default.xml can be generated. When that JIRA is resolved, we will have such an ability.

JIRA - https://issues.cask.co/browse/CDAP-3704.

**Comment by awholegunch** [comment]
okey...but what about this PR? I would like to implement Derek's suggestion, today, and then the bigger issue will get fixed when that Issue is taken up...

**Comment by awholegunch** [comment]
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB50-1)

[Revised documentation of cdap-site.xml](http://builds.cask.co/artifact/CDAP-DOB50/shared/build-1/Docs-HTML/3.2.1/en/admin-manual/installation/cdap-site.html#appendix-cdap-site-xml)

**Comment by sreevatsanraman** [comment]
I am fine with the current grouping by component.

**Comment by awholegunch** [comment]
Passes [Quick Build, Build #2](http://builds.cask.co/browse/CDAP-DOB50-2)

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Comment by awholegunch** [comment]
Sree said:
```
​[6:58 PM] sree @jj:  LGTM

**Pull request merged**
