### PR TITLE
Added CLI for getting currently executing nodes for the Workflow.

### PR DESCRIPTION
**Pull request by sagarkapare**

### CODE REVIEW

**Comment by sagarkapare** [comment]
Build is running here - http://builds.cask.co/browse/CDAP-RBT192-1

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Comment by sagarkapare** [comment]
Build is running here which includes the last change - http://builds.cask.co/browse/CDAP-RBT192-2

**Comment by sagarkapare** [comment]
Build passed. Merging..

**Pull request merged**
