### PR TITLE
Use LinkedHashSet to preserve the ordering of the classloader resourses.

### PR DESCRIPTION
**Pull request by sagarkapare**
Jira: https://issues.cask.co/browse/CDAP-2491

### CODE REVIEW

**Comment by sagarkapare** [comment]
@chtyim please review. Thanks!

**Comment by chtyim** [comment]
LGTM. Good catch.

**Comment by sagarkapare** [comment]
Develop build is running here - http://builds.cask.co/browse/CDAP-DUT1820-1

**Comment by sagarkapare** [comment]
Build passed - http://builds.cask.co/browse/CDAP-DUT1820-3. Merging.

**Pull request merged**
