### PR TITLE
Feature/cdap 2638 fix immutability of client configs

### PR DESCRIPTION
**Pull request by rohanahata**
This pull request aims to make clientconfigs immutable. All dependent calls have been rerouted through the builder.

### CODE REVIEW

**Comment by anwar6953** [comment]
Just to clarify, this will have conflicts with: https://github.com/caskdata/cdap/pull/2817
So once one is merged, the other will need additional changes, right?

**Comment by rohanahata** [comment]
@anwar6953 Yes. Both are standalone atm... once one gets modified the other will have to be changed accordingly

**Comment by anwar6953** [comment]
And just to clarify:
Doing the following:
```java
new ClientConfig.Builder().setNamespace(myNamespace). setConnectionConfig(myConnectionConfig).build()
```
will result in a ClientConfig in which the `myNamespace` being set is not necessarily there, because the `myConnectionConfig` overrode it.

I'm not sure if that's desirable or not, but definitely wanted to point it out.

**Comment by rohanahata** [comment]
@anwar6953 Addressed the issue that you brought up

**Comment by rohanahata** [comment]
CLI works on the premise that there is one ClientConfig and mutating that affects everything. If we were to implement ClientConfigs immutably, a major chunk of CLIMain would have to be refactored. After discussing with @chtyim and @gsps1 we came to the conclusion to close this PR.

**Pull request closed without merging**
