### PR TITLE
adds namespace dropdown to header

### PR DESCRIPTION
**Pull request by astewes**
*  Adds namespace dropdown to Hydrator header/navbar
*  Updates nav links (My Pipelines, Create Pipeline) to account for namespace
*  Adjusts z-indexes to ensure proper stacking (i.e., maximized console, top panel tooltips, etc.)

ns

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@astewes On click on the dropdown the down-arrow disappears. It sort of loses the dropdown effect. Is that intentional? We don't have dropdowns like this anywhere either in hydrator or cdap.

**Comment by ajainarayanan** [comment]
Also not sure if this will be an issue but the tooltip for the buttons can't we show them on the bottom rather than on the top? As a user I am most likely going to go to the namespace dropdown via one of the action buttons and would surely have the tooltip in between momentarily before clicking on the namespace dropdown. @nitinmotgi , Brady Thoughts?

**Comment by ajainarayanan** [comment]
Apart from the design questions this PR LGTM :+1:

**Comment by astewes** [comment]
@ajainarayanan per @seanouyang the namespace dropdown arrow will not be displayed when the dropdown menu is active.

**Comment by nitinmotgi** [comment]
LGTM :+1:

**Pull request merged**
