### PR TITLE
Fix HTTP endpoint for listing streams

### PR DESCRIPTION
**Pull request by jwang47**
http://builds.cask.co/browse/CDAP-DUT1602

### CODE REVIEW

**Comment by anew** [comment]
LGTM. Why is it closed?

**Comment by jwang47** [comment]
Other PR is closed, not this one. Will merge after build passes.

**Comment by anew** [comment]
I think the other PR should still change it to StreamDetail

**Comment by jwang47** [comment]
Oh, true. Will reopen it.

**Pull request merged**
