### PR TITLE
fixes minor styling issues affecting error popover in global navbar

### PR DESCRIPTION
**Pull request by astewes**
*  Fixes border issue affecting error popover arrow
*  Fixes padding/alignment of badge notification numbers within error popover

popover

### CODE REVIEW

**Comment by elfenheart** [comment]
:+1: LGTM

**Comment by ajainarayanan** [comment]
@astewes @elfenheart Added the fix for navbar to show profile & login,logout links. Those were broken on new navbar re-write.

**Comment by elfenheart** [comment]
:+1: LGTM

**Comment by elfenheart** [comment]
:+1: LGTM

**Pull request merged**
