### PR TITLE
CDAP-3827 Explain lineage JSON output

### PR DESCRIPTION
**Pull request by poornachandra**

### CODE REVIEW

**Comment by poornachandra** [comment]
Doc build - http://builds.cask.co/browse/CDAP-DDB18-1

**Comment by awholegunch** [comment]
I've edited this. LGTM, but please check my commit.

**Comment by awholegunch** [comment]
I restarted the build because the way it was originally would not have looked very good.
http://builds.cask.co/browse/CDAP-DDB18-2

**Comment by awholegunch** [comment]
Build succeeded. See results at: http://builds.cask.co/artifact/CDAP-DDB18/shared/build-2/Docs-HTML/3.2.0-SNAPSHOT/en/reference-manual/http-restful-api/metadata.html#viewing-lineages

**Comment by bdmogal** [comment]
LGTM

**Pull request merged**
