### PR TITLE
[CDAP-5638] [CDAP-5001] Feature/ui download query direct stream

### PR DESCRIPTION
**Pull request by elfenheart**

### CODE REVIEW

**Comment by ajainarayanan** [comment]
One thing I noticed is the modal seems to go away on escape whereas the upload is happening in the background for a really long time. We might want to have the modal non-closable until the upload completes or show the upload animation not using progress bar.

**Comment by elfenheart** [comment]
@ajainarayanan If we want to do that, we should do that in separate PR/JIRA since it has nothing to do with downloading query

**Comment by ajainarayanan** [comment]
:+1: LGTM

**Comment by elfenheart** [comment]
demoed to @sreevatsanraman

**Pull request merged**
