### PR TITLE
CDAP-3635: Move metadata handlers into DatasetOpExecutorService

### PR DESCRIPTION
**Pull request by jwang47**
https://issues.cask.co/browse/CDAP-3635
http://builds.cask.co/browse/CDAP-RBT439

- [ ] Test on cluster

### CODE REVIEW

**Comment by bdmogal** [comment]
@jwang47 ``RouterPathTest`` will need to be updated too?

**Comment by jwang47** [comment]
Updated `RouterPathTest`

**Comment by chtyim** [comment]
Why closed?

**Comment by jwang47** [comment]
@chtyim It's not possible move metadata handlers into cdap-data-fabric since the metadata handlers depend on LineageGenerator which depends on cdap-app-fabric (Store).

**Pull request closed without merging**
