### PR TITLE
(CDAP-2423) Skip synthetic methods when inspecting flowlet methods.

### PR DESCRIPTION
**Pull request by chtyim**
Without this, unit test "TestFrameworkTestRun.testGenerator()" fails.

### CODE REVIEW

**Comment by chtyim** [comment]
It's new in Java 7.

**Comment by anew** [comment]
LGTM.

**Comment by sreevatsanraman** [comment]
Build. http://builds.cask.co/browse/CDAP-RBT266

**Comment by sreevatsanraman** [comment]
Build passed merging.

**Pull request merged**
