### PR TITLE
Create notification threshold config inside StreamConfig

### PR DESCRIPTION
**Pull request by jguery**
This PR includes changes of https://github.com/caskdata/cdap/pull/1079.

Give the ability to modify the threshold, in a stream, after which a notification is sent. This config is put in the ``StreamConfig``.

Build: https://builds.cask.co/browse/CDAP-RBT74

### CODE REVIEW

**Comment by chtyim** [comment]
Since you are adding a new value to `StreamConfig`, mean sure when deserializing existing config.json (in `StreamAdmin`), you provide default value (the one in cConf), otherwise you might get NPE.

**Comment by jguery** [comment]
I put a default value, 1000, in the default constructor of ``StreamConfig``. Which is not great, because the default value is defined in the ``CConfiguration``. Is there a way to pass the CConfiguration to the ``StreamConfig``?

**Comment by chtyim** [comment]
It's better done in the `AbstractStreamFileAdmin`. You can have the threshold value of type `Long` instead of `int` so that `null` can be assigned from Gson. If you look at the `loadConfig` method, you'll see you can have different value then the one deserialized from gson.

**Comment by chtyim** [comment]
LGTM

**Pull request merged**
