### PR TITLE
Hotfix/temp fix flow change instances

### PR DESCRIPTION
**Pull request by chtyim**
It includes fixes for CDAP-1951 and CDAP-1996.

- CDAP-1951. It just a temp fix to make changing flowlet instances less easy to fail.
- CDAP-1996. It fixes the problem of wrongly deleting queue states when two queues share the same queue name prefix.

### CODE REVIEW

**Comment by chtyim** [comment]
Build: http://builds.cask.co/browse/CDAP-RBT283-1

**Comment by awholegunch** [comment]
What should be added to the release notes about this? Will this be a 3.0.1?

**Comment by chtyim** [comment]
Yes 3.0.1. The main fix is CDAP-1996.

**Comment by chtyim** [comment]
Build passed. Merging.

**Pull request merged**
