### PR TITLE
Feature/ui hydrator dataflow fix

### PR DESCRIPTION
**Pull request by ajainarayanan**
The aim of this PR is to have a better clarity in communication between components in UI in hydrator detailed view. Its a sort of a different attempt to bring up a pattern in UI for inter-related components in UI.

- Sort of a [```Flux```](https://facebook.github.io/flux/docs/overview.html#structure-and-data-flow) architecture
  - Action - Visible to the view (controller). Used by view to perform an action
    - Eg: Start or Stop a pipe, Choose a plugin to view its properties etc,
  - Store - One source of data for the view (controller) to render. Defines the default state of view (with no data from backend) and always provide update on data to all views listening for the change of its state (whenever the state of the store changes).
   - Dispatcher - A local pub-sub implementation used by every datastore listening to a specific action

If this works out based on,
  - Better readability (easy to understand)
  - Better debugging capabilities (to debug where an event happens and what is the state of a store at any point in time to understand what action causes what changes in a store and what affects the view).

then we should do the same for hydrator studio view. It will be a much complex change but it will help in the long run when we want to add or remove something.

##### TODO:
 - Bamboo build
 - GIF

### CODE REVIEW

**Comment by elfenheart** [comment]
delete in detail view seems to delete all apps...

**Comment by ajainarayanan** [comment]
@elfenheart 
- Fixed the delete functionality
- Fixed detailed node configurations (showing with proper config).

**Comment by elfenheart** [comment]
:+1: LGTM

**Comment by ajainarayanan** [comment]
Waiting for build: http://builds.cask.co/browse/CDAP-DRC2858-15
Waiting to create a cluster.

**Comment by ajainarayanan** [comment]
@elfenheart http://latestdevelop3795-1000.dev.continuuity.net:9999/ cluster to play around.

**Comment by ajainarayanan** [comment]
@elfenheart Rebased and beamed the latest to the cluster.

**Comment by elfenheart** [comment]
LGTM

**Pull request merged**
