### PR TITLE
CDAP-1114 enabling exploration on a stream or dataset that

### PR DESCRIPTION
**Pull request by albertshau**
already has exploration enabled should not be an error.

### CODE REVIEW

**Comment by albertshau** [comment]
https://builds.cask.co/browse/CDAP-RBT70

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by sreevatsanraman** [comment]
We need to think this through. What is we create with a different schema? Then the hive table will exists with old schema?

**Comment by albertshau** [comment]
there is no concept of schema in the api.  All you can do is enable or disable exploration, so the way you would update the schema both now and after this change is to disable then enable exploration.

**Comment by albertshau** [comment]
briefly discussed with Andreas.  The thinking is that since the api only exposes enable and disable, but not any other information like schema or table name, then enabling something that is already enabled is not an error. Similarly, disabling something that is already disabled is not an error.  Like flipping a light switch on when it is already on.

If we introduce the ability to set some configuration - such as schema - then this api should change, where we do a PUT on some existing resource instead of a POST on some action.  This is probably where we want to get to, but is not the state of the current api.

**Pull request merged**
