### PR TITLE
Fix/cherry pick 4133 to 3.2.0

### PR DESCRIPTION
**Pull request by sagarkapare**
Cherry-pick from #4429 and resolved conflicts.

### CODE REVIEW

**Comment by gsps1** [comment]
LGTM. merge with successful build

**Comment by sagarkapare** [comment]
Build is running here - http://builds.cask.co/browse/CDAP-RT321-2

**Comment by gsps1** [comment]
lgtm

**Comment by sagarkapare** [comment]
Build is green. Merging.

**Pull request merged**
