### PR TITLE
CDAP-4366: Stream Views RESTful API throws IAE instead of returning 404

### PR DESCRIPTION
**Pull request by jwang47**
https://issues.cask.co/browse/CDAP-4366
http://builds.cask.co/browse/CDAP-RBT527

### CODE REVIEW

**Comment by anwar6953** [comment]
LGTM

**Comment by jwang47** [comment]
The response message was the issue, rather than the response code. We don't have any test statements checking the message, so adding a test case for the response message would require refactoring. I'd rather avoid conflicts with https://github.com/caskdata/cdap/pull/4714, so I didn't add any test case here.

**Comment by anwar6953** [comment]
@jwang47
It seems like the response code also had a change (was 404 before this PR), right?
Also, since https://github.com/caskdata/cdap/pull/4714 is merged now, can we add a test case for this now, without introducing conflicts?

**Comment by jwang47** [comment]
The response code is the same. This PR only changes the response body.

**Comment by anwar6953** [comment]
I was under the assumption that the response code was 400 when it was IllegalArgumentException.
I see there's already test cases which assert against the response code:
https://github.com/caskdata/cdap/blob/develop/cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamViewHttpHandlerTest.java#L58-L63

**Comment by anwar6953** [comment]
LGTM. merging.

**Comment by jwang47** [comment]
Thanks @anwar6953.

**Pull request merged**
