### PR TITLE
(CDAP-4383) Make Location URI works in HDFS HA mode

### PR DESCRIPTION
**Pull request by chtyim**
- Replace calls to Location.toURI() to Loctions.toURI(Location).

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
Build: http://builds.cask.co/browse/CDAP-DUT3278-3

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Comment by sreevatsanraman** [comment]
Build passed merging.

**Comment by anew** [comment]
One risk with this fix is that anybody who does not know about this can reintroduce the bug by using Location.toURI(). How would he know? That is a method of every location and nothing tells developers that it is problematic. The better fix would be to fix it in Location itself. I know that would require Twill change and release, but I would like to suggest that in addition.

**Comment by chtyim** [comment]
Yes. The current fix is temporary.

**Pull request merged**
