### PR TITLE
Add Cask headers to shell scripts

### PR DESCRIPTION
**Pull request by wolf31o2**
I broke the RAT check! Oh noes! Fixing. :smile:

### CODE REVIEW

**Comment by albertshau** [comment]
cdap-distributions/src/packer/files/preseed.cfg still causes it to fail.

**Comment by albertshau** [comment]
for future reference, you can reproduce by running 'mvn clean package -DskipTests'

**Comment by wolf31o2** [comment]
Meh... thanks

**Comment by albertshau** [comment]
:+1:

**Pull request merged**
