### PR TITLE
(CDAP-5709) Make Schema class serializable.

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by albertshau** [comment]
lgtm

**Comment by prinam** [comment]
Build running here: http://builds.cask.co/browse/CDAP-DUT4020

**Comment by anwar6953** [comment]
Build failed on a test case also failing on develop branch; filed a JIRA (and taking an initial look) for it - https://issues.cask.co/browse/CDAP-5734

Rerunning build.

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DUT4020

**Pull request merged**
