### PR TITLE
Revert "Increase perm gen memory"

### PR DESCRIPTION
**Pull request by gsps1**
This reverts commit d210234cdc44059f421ea31880fac390f213efb2.

### CODE REVIEW

**Comment by anwar6953** [comment]
Maybe we should do this at the beginning of 3.5.0.
That way, in case there’s any other issues, we’ll have the whole release for them to surface.
No harm in having the increased perm gen either for 3.4.0.

**Comment by anwar6953** [comment]
@chtyim , what do you think?

**Comment by anwar6953** [comment]
"Just keep it at 256m.
the important thing is it doesn’t leak.
and depending on how many concurrent programs people runs in SDK, it may need more permgen
and in Java8, permgen is gone"
- Terence

**Comment by chtyim** [comment]
Also, 128m is not enough to run fork in workflow. So, let's keep it at 256

**Pull request closed without merging**
