### PR TITLE
CDAP-1585: Refactor AsciiTable usage to be pluggable

### PR DESCRIPTION
**Pull request by jwang47**
Instead of `new AsciiTable(header, records, rowMaker).print(output)`, we now do

```
Table table = Table.builder()
  .setHeader(..)
  .setRows(records, rowMaker)
  .build();
tableRenderer.render(output, table);
```

where tableRenderer implements

```

public interface TableRenderer {
  /**
   * Renders the table to the output.
   *
   * @param output the output to render to
   * @param table the table to render
   */
  void render(PrintStream output, Table table);
}
```

This is done to allow `CLIMainTest` to use a more simple table renderer.

### CODE REVIEW

**Comment by jwang47** [comment]
http://builds.cask.co/browse/CDAP-DUT884

**Comment by albertshau** [comment]
lgtm

**Comment by albertshau** [comment]
@jwang47 are we waiting on something to merge this?

**Comment by jwang47** [comment]
Working on getting the build to pass.

**Comment by jwang47** [comment]
Tests passed in all modules except for FileSet Example, which wasn't affected by this PR. Merging. http://builds.cask.co/browse/CDAP-DUT884-13/test

**Pull request merged**
