### PR TITLE
Update the copyright header for CDAP from 2014 to 2014-2015

### PR DESCRIPTION
**Pull request by henry-cask**
This PR Contains large number of files but the goal is to change copyright header year.

The copyright information in the header need to be updated to reflect 2015.

From: Copyright © 2014 Cask Data, Inc.
To: Copyright © 2014-2015 Cask Data, Inc.

### CODE REVIEW

**Comment by henry-cask** [comment]
Build:
http://builds.cask.co/browse/CDAP-DUT2565-2

**Comment by sagarkapare** [comment]
@henry-cask I think we only update the copyright if the file is modified? Are these the files we modified in 2015 and missed to update the copyright?

**Comment by henry-cask** [comment]
Copyright only applies to whatever year posted in the header regardless been modified or not.

So for the files not modified, the Copyright end by end of year 2014

**Comment by bdmogal** [comment]
Presuming this is necessary, and build passes, LGTM.

**Comment by henry-cask** [comment]
Thanks, merging ...

**Comment by awholegunch** [comment]
I missed this PR and issue. This is unnecessary and should not have been done. Especially since changing file hashes are used to flag real changes in the documentation, and this sort of change breaks the documentation build.

Copyright does not end at the end of a year. The year signifies when the copyright starts. In the case of corporations in the United States, the length of term is 120 years. (See http://www.copyright.gov/title17/92chap3.html#302).

Please revert this merge.

**Comment by henry-cask** [comment]
Ah, then I think we need change some. I remember seeing some has 2014-2015. Ok reverting this change

**Pull request merged**
