### PR TITLE
Changes for spark driver to use more Perm memory

### PR DESCRIPTION
**Pull request by CuriousVini**
Changes for spark driver to use more perm memory.

Issue: https://issues.cask.co/browse/CDAP-5768
Build: http://builds.cask.co/browse/CDAP-DUT4064-1

### CODE REVIEW

**Comment by anwar6953** [comment]
Similar to: https://github.com/caskdata/cdap/pull/5641

**Comment by chtyim** [comment]
LGTM

**Comment by rohitsinha54** [comment]
if building locally passes merge

**Comment by CuriousVini** [comment]
@rohitsinha54 build passed locally.

**Comment by CuriousVini** [comment]
Merging.

**Pull request merged**
