### PR TITLE
Updating version to 2.8.3

### PR DESCRIPTION
**Pull request by wolf31o2**
Updated version to 2.8.3 in the same manner as done in #3173

### CODE REVIEW

**Comment by anwar6953** [comment]
I think we should keep this as the last code change to release/2.8 before the release of 2.8.3 (so not merge it yet). At least, that's what we usually do, right?
@bdmogal ?

**Comment by bdmogal** [comment]
First step of the release process. The only thing that may go wrong is if it pushes 2.8.3 artifacts before we're ready to release.

**Comment by sagarkapare** [comment]
Should not we upgrade to 2.8.3-SNAPSHOT and before releasing change it to the 2.8.3?

**Comment by anwar6953** [comment]
I don't think we do that for release branches.

**Comment by sagarkapare** [comment]
Discussed with @sreevatsanraman and its fine to upgrade to 2.8.3

**Comment by anwar6953** [comment]
Oh, how did you notice that the version-bumping was missing from archetype?

**Comment by sagarkapare** [comment]
`grep` for 2.8.2 for verification.

**Comment by anwar6953** [comment]
LGTM

**Pull request merged**
