### PR TITLE
CDAP-4340 Added documentation for accessing MapReduce counters from the WorkflowToken.

### PR DESCRIPTION
**Pull request by sagarkapare**
JIRA: https://issues.cask.co/browse/CDAP-4340

### CODE REVIEW

**Comment by awholegunch** [comment]
I have looked at the docs, and revised them and the Javadoc comments. LGTM, but please review.

**Comment by awholegunch** [comment]
I think there is now an error in the documentation; at the end of this page there is an example, and that is probably no longer correct. [The Workflow Example](http://docs.cdap.io/cdap/current/en/developers-manual/building-blocks/workflows.html#example-of-using-a-workflow) has:
```
  // To get the most recent value of counter with group name
  // 'org.apache.hadoop.mapreduce.TaskCounter' and counter name 'MAP_INPUT_RECORDS':

  String flattenCounterKey = "mr.counters.org.apache.hadoop.mapreduce.TaskCounter.MAP_INPUT_RECORDS";
  workflowToken.get(flattenCounterKey, WorkflowToken.Scope.SYSTEM);

  // To get the value of counter with group name
  // 'org.apache.hadoop.mapreduce.TaskCounter' and counter name 'MAP_INPUT_RECORDS' as
  // set by a MapReduce program with unique name 'PurchaseHistoryBuilder':

  workflowToken.get(flattenCounterKey, "PurchaseHistoryBuilder", WorkflowToken.Scope.SYSTEM);
```
For the second example, ``flattenCounterKey`` should not start with ``mr.counters.``. I don't know about the first. Correct? If so, I can make that change...

**Comment by awholegunch** [comment]
I've updated the example. Please review.

**Comment by anwar6953** [comment]
@jj I agree that `flattenCounterKey` should not start with `mr.counters.`.

**Comment by awholegunch** [comment]
LGTM

**Comment by anew** [comment]
Is this complete? The Jira explicitly mentions to document:

2. How to read the custom counters from the WorkflowToken

I don't see that as part of the PR

**Comment by anwar6953** [comment]
Closing; this documentation PR will have to be reopened against release/3.3 branch

**Pull request closed without merging**
