### PR TITLE
Update to 3.3.3

### PR DESCRIPTION
**Pull request by sreevatsanraman**
Ran a local build and it ran fine
```
[INFO] CDAP MapReduce Archetype .......................... SUCCESS [0.254s]
[INFO] CDAP Application Archetype ........................ SUCCESS [0.268s]
[INFO] CDAP Integration Test Framework ................... SUCCESS [0.929s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:23.693s
[INFO] Finished at: Thu Apr 14 17:13:31 PDT 2016
[INFO] Final Memory: 198M/732M
[INFO] -----------------------------------------------------------------------
```

### CODE REVIEW

**Comment by wolf31o2** [comment]
:+1: LGTM

**Comment by anwar6953** [comment]
Two files which probably need updating (I was updating them in the script, but had them commented out, for some reason...):
https://github.com/caskdata/cdap/blob/500525ba4be07a6ab50ad5afa539cf0ccda4bc2c/cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
https://github.com/caskdata/cdap/blob/500525ba4be07a6ab50ad5afa539cf0ccda4bc2c/cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json

Maybe this one also: @dereklwood @wolf31o2 ?
https://github.com/caskdata/cdap/blob/500525ba4be07a6ab50ad5afa539cf0ccda4bc2c/cdap-distributions/src/hdinsight/install.sh

**Comment by sreevatsanraman** [comment]
@anwar6953 fixed.

**Comment by anwar6953** [comment]
LGTM

**Comment by wolf31o2** [comment]
The JSON files define a variable that were override in our build. It should be done, but isn't required for release. Same with the hdinsight script...

**Pull request merged**
