### PR TITLE
CDAP-3535 giving programs access to the app spec

### PR DESCRIPTION
**Pull request by albertshau**
This involves moving ApplicationSpecification back into cdap-api,
as well as removing access to internal classes from the spec.

### CODE REVIEW

**Comment by albertshau** [comment]
http://builds.cask.co/browse/CDAP-DUT2658

**Comment by gokulavasan** [comment]
I didn't see any new unit tests to verify the program spec in an app? Do we need one?

Changes LGTM :+1:

**Comment by albertshau** [comment]
i'll add a test

**Comment by gokulavasan** [comment]
LGTM :+1:

**Pull request merged**
