### PR TITLE
Copy the source files to archetype files and replace the package name.

### PR DESCRIPTION
**Pull request by anwar6953**
Update archetypes, based upon their corresponding sources.

### CODE REVIEW

**Comment by anwar6953** [comment]
The archetype files on release/3.3 show `2014-2015` in their copyright, but the example sources only had `2014`, so updated the example sources to also be `2014-2015`.

**Comment by sreevatsanraman** [comment]
LGTM Please merge once this is tested.

**Comment by anwar6953** [comment]
While testing the archetypes, I found compilation issues because SparkKMeansProgram and SparkPageRankAppTest were using package-specifying imports, so just copying over the sources gave compilation issues.
Updated those classes to not use package-specifying imports.

Tested the archetypes out now with these changes. :+1:

**Comment by anwar6953** [comment]
Squashed and merged.

**Pull request merged**
