### PR TITLE
Feature adapter/onfinish batch adapter

### PR DESCRIPTION
**Pull request by gokulavasan**
* Fix a bug in ETLTemplate : Same prefix id should be used for both registering and loading plugins.

### CODE REVIEW

**Comment by gokulavasan** [comment]
Build : http://builds.cask.co/browse/CDAP-RT25-17

**Comment by bdmogal** [comment]
:+1: wish there was a test that could catch this.

**Comment by gokulavasan** [comment]
Build : http://builds.cask.co/browse/CDAP-RT25-18

**Comment by gokulavasan** [comment]
Build passed. Merging.

**Pull request merged**
