### PR TITLE
Refactor + bug fix of UsageDataset

### PR DESCRIPTION
**Pull request by chtyim**
Spotted this problem when fixing CDAP-2495 (fixing guice module along the way).

- Add UsageDataset as a system dataset module
- Make DatasetFrameworkTestUtil use SystemDataset guice module
- Remove dependency on TransactionExecutorFactory in InMemoryDatasetFramework

### CODE REVIEW

**Comment by abaranau** [comment]
LGTM

**Comment by jwang47** [comment]
LGTM

**Comment by jwang47** [comment]
LGTM

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-RBT291

**Comment by chtyim** [comment]
Squashed commits. Merging.

**Pull request merged**
