### PR TITLE
Bump version to 3.3.2 (remove snapshot)

### PR DESCRIPTION
**Pull request by anwar6953**
Bump version to 3.3.2 (remove snapshot)

### CODE REVIEW

**Comment by anwar6953** [comment]
Just one pending question. @dereklwood 

Do we want to bump this version, or is the current value being depended on somewhere?
https://github.com/caskdata/cdap/blob/release/3.3/cdap-distributions/src/hdinsight/install.sh#L39

**Comment by dereklwood** [comment]
We can go ahead and bump it.  Only a testing template i'm using will break until the packages are available.  In general, once this is launched, actual traffic will use a released version of the script (as an artifact), so generally we will want to update it along with everything else

**Comment by anwar6953** [comment]
Alright. Included this change:
image

**Comment by awholegunch** [comment]
LGTM

**Pull request merged**
