### PR TITLE
Revert "[CDAP-3077] Added another config parameter in Table Sink to a…

### PR DESCRIPTION
**Pull request by bdmogal**
Reverts caskdata/cdap#3366

### CODE REVIEW

**Comment by albertshau** [comment]
we shouldn't have to revert this right? just cherry-pick onto release?

**Comment by bdmogal** [comment]
I had based this branch off of 3.1. Was wondering if that would cause issues? But since there were no merge conflicts, I guess that should be ok?

**Comment by albertshau** [comment]
im not sure what happens if you revert a change here, cherry-pick the unreverted changes to release, then merge release here.

**Comment by bdmogal** [comment]
Ok, let's just merge #3391 then, and close this, but keep the branch?

**Comment by sreevatsanraman** [comment]
@bdmogal  should we close this PR?

**Pull request closed without merging**
