### PR TITLE
CDAP-665: Add a Custom 404 Error Page

### PR DESCRIPTION
**Pull request by awholegunch**
- Adds a 404 page to the CDAP docs. (https://issues.cask.co/browse/CDAP-665)
- Make the placeholder be an "_rst" file, to make the build script simpler. That way, all rst files cane be copied in one command.

404 Page is staged at:
http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-2.7.0_404_page/en/404.html

(The web server is not configured for a custom 404 page, but that's a different issue.)

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
The changes looks awesome in-terms of content. Perhaps we can add a logo as well. 

Please see http://cask.co/404

**Comment by awholegunch** [comment]
Beyond the logo in the upper-left? I'm using the same theme as the other pages; which has plusses and minuses: the plus being that it looks familiar to the user; the minus being it doesn't look much different than the other pages...

**Comment by awholegunch** [comment]
New image can be seen at: http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-2.7.0_404_page/en/404.html

**Comment by sreevatsanraman** [comment]
lgtm :+1:

**Pull request merged**
