### PR TITLE
Make sure the config table is dropped only after all queue data tables are dropped.

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by ghelmling** [comment]
lgtm

**Comment by chtyim** [comment]
Build running in http://builds.cask.co/browse/CDAP-DUT1042

**Comment by chtyim** [comment]
A totally unrelated test failed. Rerunning build at http://builds.cask.co/browse/CDAP-DUT1042-2

**Comment by chtyim** [comment]
Test passed. Merging.

**Pull request merged**
