### PR TITLE
Remove cdap-etl-lib and cdap-etl-common modules from CDAP.

### PR DESCRIPTION
**Pull request by anwar6953**
http://builds.cask.co/browse/CDAP-RBT587-9
https://issues.cask.co/browse/CDAP-4415
https://issues.cask.co/browse/CDAP-4416

Removing modules: 'cdap-etl-lib' and 'cdap-etl-common'.
This code has been migrated to the hydrator-plugins repo, since it is mostly for application code.

### CODE REVIEW

**Comment by albertshau** [comment]
lgtm, though please dont merge until integration tests can run without it

**Comment by anwar6953** [comment]
@albertshau I had to copy over ETLUtils and StreamBatchSource because they're used by DataQualityAppTest.

**Comment by albertshau** [comment]
lgtm

**Comment by anwar6953** [comment]
@albertshau When I was trying the branch on an autobuild cluster, I noticed some errors. Turns out I still had to remove references to cdap-etl-lib from pom files.
Could you please review the last commit, which is new?
Thanks.

**Comment by albertshau** [comment]
lgtm

**Comment by awholegunch** [comment]
Starting a Quick Build to check the docs after this change: http://builds.cask.co/browse/CDAP-DOB84-1

**Comment by elfenheart** [comment]
lgtm on UI changes

**Comment by anwar6953** [comment]
Build green; squashed the commits to 3, organized commits.

**Pull request merged**
