### PR TITLE
CDAP-2896 Update dependency to Tephra 0.5.1

### PR DESCRIPTION
**Pull request by ghelmling**
Updates CDAP to use a snapshot build of Tephra 0.5.1.

NOTE: the PR to update CDAP to use Twill 0.6.0-incubating-SNAPSHOT must be merged before this PR -- https://github.com/caskdata/cdap/pull/3074

### CODE REVIEW

**Comment by chtyim** [comment]
Changes LGTM. Will wait for the test build.

**Comment by chtyim** [comment]
Build passed http://builds.cask.co/browse/CDAP-DUT2135

**Comment by sreevatsanraman** [comment]
commit 324d267 looks good.

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Pull request merged**
