### PR TITLE
remove capitalization for apps dataset streams programs

### PR DESCRIPTION
**Pull request by elfenheart**
Remove capitalizations on title for Programs, Apps, Dataset, Streams

### CODE REVIEW

**Comment by anwar6953** [comment]
I pushed a couple more removals. Check 'em out.

**Comment by anwar6953** [comment]
Do we also want to remove it from ETL property names?
`/cdap/cdap-ui/app/features/etlapps/templates/create/tabs/sinkPropertyEdit.html` line 12

**Comment by nitinmotgi** [comment]
It's ok! @anwar6953. We don't need it there.

**Comment by nitinmotgi** [comment]
LGTM :+1:

**Pull request merged**
