### PR TITLE
CDAP-3854: Remove upgrade for templates and adapters (CDAP-3490) and apps (CDAP-3451)

### PR DESCRIPTION
**Pull request by rohitsinha54**
This removes the upgrade step added in these PR for 3.2
1. https://github.com/caskdata/cdap/pull/3786
2. https://github.com/caskdata/cdap/pull/3706

### CODE REVIEW

**Comment by albertshau** [comment]
:+1:

**Comment by rohitsinha54** [comment]
Testing on cluster for the current upgrade steps to work from 3.2 to develop before merging.

**Comment by rohitsinha54** [comment]
Build:http://builds.cask.co/browse/CDAP-DUT2954-3

**Comment by rohitsinha54** [comment]
@albertshau : ApplicationLifecycleServiceTest was deleted in this PR but looks like you added a new test in it which does not do upgrade testing so while resolving conflicts I have preserved it. Can you please have a look at ApplicationLifecycleServiceTest in this PR again and make sure your needed changes are intact. Thanks.

**Comment by albertshau** [comment]
:+1:

**Pull request merged**
