### PR TITLE
CDAP-5460 Fix to update Spark program's status when it is running as a part of Workflow.

### PR DESCRIPTION
**Pull request by sagarkapare**
JIRA: https://issues.cask.co/browse/CDAP-5460

### CODE REVIEW

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by sagarkapare** [comment]
Build is running here - http://builds.cask.co/browse/CDAP-DUT3836-1

**Comment by sagarkapare** [comment]
Thanks @gokulavasan. will merge once build succeeds.

**Comment by sagarkapare** [comment]
Build is green here - http://builds.cask.co/browse/CDAP-DUT3836-JOB1-2. Merging.

**Pull request merged**
