### PR TITLE
Increase resources for Page Rank sample app to be successful in workflow

### PR DESCRIPTION
**Pull request by henry-cask**
The SparkPageRankApp is being used in the workflow where the workflow driver need to share memory with Spark runner.

Need to add more resources to SparkPageRankSpecification to make sure it runs otherwise the container will randomly throw out of memory that restart the workflow app container.

### CODE REVIEW

**Comment by rohitsinha54** [comment]
LGTM

**Comment by awholegunch** [comment]
-1

**Comment by awholegunch** [comment]
You need to check if this page is included in another file. If it is, the hash change will break the doc build.

**Comment by awholegunch** [comment]
As it is included, these changes will probably put the include out of alignment. (which is why we have guards!) Can you look and see what changes are needed to the doc that references this? It's the example page for this App. If you need help, ask...

**Comment by henry-cask** [comment]
@awholegunch thanks, will check for it.

**Comment by rohitsinha54** [comment]
You will just need to update the hash. As we don't show these lines in docs. The doc for this example need not to be updated.

**Comment by awholegunch** [comment]
@rohitsinha54 Since one line was added (19) before the include, it shifts everything by one line, and the including file needs adjusting. Otherwise, an out-by-one error.

**Comment by awholegunch** [comment]
@henry-cask 's on it.

**Comment by henry-cask** [comment]
Update the PR and submit build to test: http://builds.cask.co/browse/CDAP-RBT394-1

**Comment by henry-cask** [comment]
@rohitsinha54 , @awholegunch could you help review again?

**Comment by awholegunch** [comment]
LGTM. You can see if you expand the GitHub diff how the lines have shifted...

**Comment by awholegunch** [comment]
I missed the part about saying what you are doing. That would be a good idea, especially if it something that people would encounter.

**Comment by awholegunch** [comment]
Let me write something up.

**Comment by awholegunch** [comment]
@henry-cask @rohitsinha54 Please review my addition

**Comment by henry-cask** [comment]
LGTM

**Comment by henry-cask** [comment]
@rohitsinha54 , @awholegunch I updated about memory usage of Spark inside workflow. Let me know what you think.

**Comment by henry-cask** [comment]
LGTM

**Comment by henry-cask** [comment]
Waiting build: http://builds.cask.co/browse/CDAP-RBT394-3

**Comment by henry-cask** [comment]
Will wait for successful build

**Comment by sreevatsanraman** [comment]
Build is :green_apple:  merging
http://builds.cask.co/browse/CDAP-RBT394-4

**Comment by henry-cask** [comment]
Successful build: http://builds.cask.co/browse/CDAP-RBT394-4

**Comment by henry-cask** [comment]
Thanks @sreevatsanraman for merging!

**Pull request merged**
