### PR TITLE
Fix ProgramClassLoader leakage, which mainly affect standalone.

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by chtyim** [comment]
Verified it doesn't break distributed mode and ClassLoaders are GC'ed correctly in Standalone.

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Comment by chtyim** [comment]
Spark is still leaking Class. Have some initial investigation and it seems the fix for Spark requires refactoring on how we run Spark in Standalone. Make that as separate effort (https://issues.cask.co/browse/CDAP-1457)

**Comment by chtyim** [comment]
Build passed, merging. http://builds.cask.co/browse/CDAP-DUT764-1

**Pull request merged**
