### PR TITLE
CDAP-4398 Revised Installation documentation

### PR DESCRIPTION
**Pull request by awholegunch**
[Quick Build 31](http://builds.cask.co/browse/CDAP-DOB73-31)

Build fails because of two guarded-file changes that aren't relevant.

**Pages of Interest:**

- [Admin Manual Index Page](http://builds.cask.co/artifact/CDAP-DOB73/shared/build-31/Docs-HTML/3.3.0-SNAPSHOT/en/admin-manual/index.html)
- [Installation Index Page](http://builds.cask.co/artifact/CDAP-DOB73/shared/build-31/Docs-HTML/3.3.0-SNAPSHOT/en/admin-manual/installation/index.html)
- [Cloudera Manager](http://builds.cask.co/artifact/CDAP-DOB73/shared/build-31/Docs-HTML/3.3.0-SNAPSHOT/en/admin-manual/installation/cloudera.html)
- [Ambari](http://builds.cask.co/artifact/CDAP-DOB73/shared/build-31/Docs-HTML/3.3.0-SNAPSHOT/en/admin-manual/installation/ambari.html)
- [MapR](http://builds.cask.co/artifact/CDAP-DOB73/shared/build-31/Docs-HTML/3.3.0-SNAPSHOT/en/admin-manual/installation/mapr.html)
- [Package Managers (RPM/Debian)](http://builds.cask.co/artifact/CDAP-DOB73/shared/build-31/Docs-HTML/3.3.0-SNAPSHOT/en/admin-manual/installation/package-managers.html)

Fixes for:
- https://issues.cask.co/browse/CDAP-4398
- https://issues.cask.co/browse/CDAP-4431
- https://issues.cask.co/browse/CDAP-4432
- https://issues.cask.co/browse/CDAP-4436
- https://issues.cask.co/browse/CDAP-4448
- https://issues.cask.co/browse/CDAP-4139

### CODE REVIEW

**Comment by awholegunch** [comment]
One further change that could be made is to take the info on the [Setting-up MapR Clients](http://builds.cask.co/artifact/CDAP-DOB73/shared/build-1/Docs-HTML/3.3.0-SNAPSHOT/en/admin-manual/installation/mapr/mapr-setting-up.html) page and add similar info to the [Package Managers Setting-up the Cluster](http://builds.cask.co/artifact/CDAP-DOB73/shared/build-1/Docs-HTML/3.3.0-SNAPSHOT/en/admin-manual/installation/package-managers/pm-setting-up.html) page. If someone can suggest what that would be exactly...

**Comment by awholegunch** [comment]
"On-hold" until the issues that surfaced in the Hackathon are resolved.

**Comment by awholegunch** [comment]
"On-hold" as I have more changes to add.

**Comment by sreevatsanraman** [comment]
LGTM

**Pull request merged**
