### PR TITLE
CDAP-1323: Remove old authorization code

### PR DESCRIPTION
**Pull request by jwang47**

### CODE REVIEW

**Comment by jwang47** [comment]
Build running https://builds.cask.co/browse/CDAP-DUT680-1

**Comment by jwang47** [comment]
Build passed https://builds.cask.co/browse/CDAP-DUT680-1

**Comment by ParthGandhi** [comment]
This is being moved to `common`, right? If so, LGTM.

**Comment by jwang47** [comment]
Actually this current code is being completely refactored and I'm going to implement authorization framework in CDAP, but the end goal is to move to common once the authorization code is stable.

**Comment by ParthGandhi** [comment]
Okay, still LGTM since these classes don't seem to be used anywhere else.

**Pull request merged**
