### PR TITLE
Cherry pick to 3.0 branch: CDAP-2475 Make the JMS source to accept type and name of the JMS provider plugin.

### PR DESCRIPTION
**Pull request by henry-cask**
Make the JMS source to accept type and name of the JMS provider plugin.

Add 2 new JMS source configuration to set the dependent plugin for JMS Connection initial context.

### CODE REVIEW

**Comment by henry-cask** [comment]
http://builds.cask.co/browse/CDAP-RBT302-1

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by henry-cask** [comment]
Thanks @gokulavasan , will wait till build pass then merge

**Comment by henry-cask** [comment]
http://builds.cask.co/browse/CDAP-RBT302-2

**Comment by henry-cask** [comment]
Build successful, merging ...

**Pull request merged**
