### PR TITLE
adds item count to opened group

### PR DESCRIPTION
**Pull request by astewes**
*  Adds badge with total item count to opened group in left side panel

badge

### CODE REVIEW

**Comment by elfenheart** [comment]
When we are filtering the list, do we want to update the count to become the filtered list or should it remain as the original count?

**Comment by ajainarayanan** [comment]
:+1: LGTM apart from @elfenheart's comment.

**Comment by elfenheart** [comment]
updated with the filtered length

**Comment by astewes** [comment]
LGTM

**Pull request merged**
