### PR TITLE
Add the ability to forcibly kill the Standalone CDAP process.

### PR DESCRIPTION
**Pull request by awholegunch**
Under Windows, the running process is forcibly killed; this adds an option to force that in the equivalent shell script.

### CODE REVIEW

**Comment by wolf31o2** [comment]
Pretty sure Windows doesn't have the equivalent signal to `kill` on *NIX and must use the equivalent of `kill -9`... What was the reason for making this change?

**Comment by awholegunch** [comment]
Under Windows (in cdap.bat), we force-kill the process: ``taskkill /F /PID %%i >NUL 2>&1``
(see https://technet.microsoft.com/en-us/library/bb491009.aspx; "/f   : Specifies that process(es) be forcefully terminated.")

We don't have a force under Unix...so I find I am often having to find the process ID, and then use kill -9...this means if the process won't stop, I can use cdap.sh to force kill it.

**Comment by chtyim** [comment]
First, why the process cannot stop normally? We shouldn't allow that to happen.

**Comment by awholegunch** [comment]
@chtyim True, the process should stop normally, but because of bugs or issues, sometimes it doesn't.

Then one is left with using kill -9. This makes it easier in those cases.

**Comment by sreevatsanraman** [comment]
We should not be doing this. If we provide this option, we won't get to the underlying issue. Let's open JIRAs for when process doesn't shutdown cleanly, attach stack trace and required details than masking the problem. 

I suggest we close this PR.

**Comment by awholegunch** [comment]
As there is a consensus to **not** do this, I will close the PR. Opened an issue to check if this should be done under Windows or not...(https://issues.cask.co/browse/CDAP-2555)

**Pull request closed without merging**
