### PR TITLE
Change Kafka source emitter to use StructuredRecord. Convert to plugin.

### PR DESCRIPTION
**Pull request by henry-cask**
This PR consists changes to make Apache Kafka realtime source to be plugin mode:
-) Emit StructuredRecord instead of ByteBuffer
-) Follow plugin mode by using PluginConfig to pass properties to Kafka source.

### CODE REVIEW

**Comment by henry-cask** [comment]
Build:
http://builds.cask.co/browse/CDAP-RT7-1

**Comment by chtyim** [comment]
LGTM

**Comment by hsaputra** [comment]
Thanks for the review, @chtyim

**Comment by henry-cask** [comment]
Awesome, thanks for the review @chtyim

**Comment by henry-cask** [comment]
Successful Build:
http://builds.cask.co/browse/CDAP-RT7

**Pull request merged**
