### PR TITLE
Add custom properties in the JMSSource config for custom JMS properties.

### PR DESCRIPTION
**Pull request by henry-cask**
Cherry pick from develop branch for 3.0.x branch

### CODE REVIEW

**Comment by henry-cask** [comment]
CC @albertshau

**Comment by henry-cask** [comment]
http://builds.cask.co/browse/CDAP-RBT303-1

**Comment by albertshau** [comment]
lgtm

**Comment by henry-cask** [comment]
Thanks Albert!

Will merge once build passes.

**Comment by albertshau** [comment]
hm the custom properties field is not rendering correctly as json. Seems like it needs to be in the "position" array.  I also think we should move it from group2 into group1, but we can do this in a separate PR.

**Comment by henry-cask** [comment]
It is already in group2 position array, isnt it?

**Comment by albertshau** [comment]
o yes sorry ignore that comment. do you think it makes more sense to be in Connection Factory group or Configuration group?

**Comment by henry-cask** [comment]
I think adding it in the Connection Factory group fits better since it is related to properties passed to the connection factory.

**Comment by albertshau** [comment]
ok sounds good

**Comment by henry-cask** [comment]
http://builds.cask.co/browse/CDAP-RBT303-2

**Comment by henry-cask** [comment]
http://builds.cask.co/browse/CDAP-RBT303-3

**Pull request merged**
