### PR TITLE
Support for CDH 5.5.0

### PR DESCRIPTION
**Pull request by sagarkapare**
JIRA: https://issues.cask.co/browse/CDAP-4301

### CODE REVIEW

**Comment by sagarkapare** [comment]
Release build is running here - http://builds.cask.co/browse/CDAP-RBT571-1. Running integration tests as well on different versions of the HBase.

**Comment by wolf31o2** [comment]
This will require [COOK-82](https://issues.cask.co/browse/COOK-82) to be resolved before it can pass automated integration tests, otherwise the package never gets installed by Chef. Will this be backported to other versions of CDAP or will this be a 3.3+ feature?

**Comment by sagarkapare** [comment]
I am running the integration tests on the custom cluster created from the auto-build template for verification. I think this will be 3.3+ feature but @poornachandra can confirm.

**Comment by poornachandra** [comment]
@wolf31o2 CDH 5.5.0 support will be CDAP 3.3+ feature

**Comment by sagarkapare** [comment]
@poornachandra release build succeeded. Also integration tests are running fine with some unrelated transient errors which I am looking into. 

Please help review this PR. Thanks!

**Comment by poornachandra** [comment]
LGTM

**Pull request merged**
