### PR TITLE
Replace non-standard LIMIT with a WHERE clause in the query to get Re…

### PR DESCRIPTION
**Pull request by bdmogal**
…sultSetMetadata

Tested on Oracle DB and HsqlDB that this is a valid query.

1st step towards getting Oracle write support.

### CODE REVIEW

**Comment by gokulavasan** [comment]
May be add a comment to say why we are executing such a query?

**Comment by gokulavasan** [comment]
Comment then LGTM :+1:

**Comment by gokulavasan** [comment]
Please open the PR against release

**Comment by anwar6953** [comment]
yea, why is it like that?

**Comment by bdmogal** [comment]
@anwar6953 the point of this query is to make a call to the table to retrieve its schema in the form of a ``ResultSetMetadata`` object. Actual queries happen via ``DBOutputFormat`` when the MapReduce program runs.

**Pull request closed without merging**
