### PR TITLE
Correct the spelling of "ZooKeeper".

### PR DESCRIPTION
**Pull request by awholegunch**
In most cases, it should be spelt "ZooKeeper". This corrects it in both the documentation and the application template. It adds Apache ZooKeeper as trademark of the Apache Foundation.

Fixes https://issues.cask.co/browse/CDAP-3375

### CODE REVIEW

**Comment by gokulavasan** [comment]
LGTM :+1: Just curious, in what cases should it not be spelt as "ZooKeeper"

**Comment by awholegunch** [comment]
I guess the only other cases are where it should be all lower-case ("zookeeper"), which is usually code or a property name. There are a number of ``Constants.Zookeeper.*``...

**Comment by awholegunch** [comment]
There are classes called ``Zookeeper``, but I have left them unchanged.

**Comment by gokulavasan** [comment]
LGTM :+1: Can you squash all the commits to a single one before merging? Or do you think they all warrant a separate commit?

**Pull request merged**
