### PR TITLE
Added copyright to all .js files

### PR DESCRIPTION
**Pull request by bdmogal**

### CODE REVIEW

**Comment by nitinmotgi** [comment]
LGTM :+1:

**Comment by anwar6953** [comment]
Should we enable the header checks for ui js files now? So new ui files are also forced to have it.

**Comment by bdmogal** [comment]
Will have to explore how to do it. maybe jslint or something like that.

**Comment by chtyim** [comment]
RAT check?

**Comment by bdmogal** [comment]
@chtyim yes, trying it out.

**Pull request merged**
