### PR TITLE
CDAP-2047: First step: Cleanup MetricsTable interface of all unused methods

### PR DESCRIPTION
**Pull request by abaranau**
Cleaning up MetricsTable interface makes it easier to implement (CDAP-2047) and later integrate into Table (CDAP-1193)

### CODE REVIEW

**Comment by abaranau** [comment]
http://builds.cask.co/browse/CDAP-DUT1387-1

**Comment by abaranau** [comment]
GREEN

**Comment by anwar6953** [comment]
whats the replacement for batch delete?

**Comment by abaranau** [comment]
it is not used now: see todo "+        // todo: do deletes efficiently, in batches, not one-by-one".

It will not be used as it was - via scan + filter, but rather it will be multi-delete

**Comment by abaranau** [comment]
so old goes away anyways, as unused

**Comment by anwar6953** [comment]
lgtm

**Pull request merged**
