### PR TITLE
Remove OperationException from MDS

### PR DESCRIPTION
**Pull request by sreevatsanraman**
OperationException existed in legacy code. We don't need it anymore, the implementation doesn't throw OperationException. 

Removing it now so that the new code that is added doesn't need to follow the same.

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
Build: https://builds.cask.co/browse/CDAP-DUT529-1

**Comment by anew** [comment]
Something that worries me here is this: Long time ago, MDS only threw operation exceptions. With datasets v2, that was changed and it now throws runtime exceptions. Obviously we don't need to catch OperationException, but should we still try to catch exceptions? I guess this is a change that should have happened when MDS was changed - when changing the exception that is thrown, we should have changed all places that used to catch the old exception. That did not happen.... but we have lots of places now where exceptions are not caught at all. I understand that this is a lot of work, and possibly impossible to find all these places (the nature of unchecked exceptions is that Java does not tell you where they are thrown). 

How comfortable are you that all code is still correct?

**Comment by anew** [comment]
Oh, and can you actually remove OperationException? Or deprecate it?

**Comment by sreevatsanraman** [comment]
@anew - I removed it only in MDS and not across all the code base, since that would require a lot more testing. The MDS calls are made via HttpHandlers. Removed all the catch blocks that handled OperationException that were resulting from MDS calls. If there are any other places where OperationException is thrown that is not handled in the HttpHandler - the router would handle it. 

So, I am confident about this change. 

There are other places where OperationException is used, but this PR only addresses MDS portion.

I will mark OperationException as deprecated

**Comment by anew** [comment]
OK. LGTM

**Comment by anew** [comment]
Sorry accidentally hit close button

**Pull request merged**
