### PR TITLE
Fix/ui remove unusedcode

### PR DESCRIPTION
**Pull request by ajainarayanan**
- Removes un-used directives
- Renames files to be consistent.

### CODE REVIEW

**Comment by elfenheart** [comment]
Need to modify Flowlet Input and Output graphs with C3 so we can deprecate Epoch.

**Comment by ajainarayanan** [comment]
I think the comment (https://github.com/caskdata/cdap/pull/3060#issuecomment-116847774) should belong here. Anyhow removed references to modules that we no longer use.

**Comment by elfenheart** [comment]
Are we still using Angular Strap *button, dropdown, and alert* modules?

**Comment by ajainarayanan** [comment]
@elfenheart Yes ```$dropdown and $alert``` services are from angular-strap. Have removed bs-button (used in some admin template which we are not using)

**Comment by elfenheart** [comment]
:+1: LGTM

**Pull request merged**
