### PR TITLE
Feature/ui hydrator diagram metrics

### PR DESCRIPTION
**Pull request by elfenheart**
metrics

### CODE REVIEW

**Comment by ajainarayanan** [comment]
Few minor things,
1. On popover on nodes we might want to display the plugin name instead of node name
2. On drag and drop of canvas on detailed view seems to drop the dag in some other place. Not sure if this got fixed.
3. I could almost reproduce it all the time but whenever I hover over the popover of a node, the popover disappears but if I hover over the node and immediately pull out, the popover stays there until I hover over the node again. Might be a little easier if we close the close popover whenever we move out of the node.

**Comment by ajainarayanan** [comment]
Otherwise LGTM

**Comment by ajainarayanan** [comment]
node popover

**Comment by elfenheart** [comment]
number 2 is fixed in another PR #4717

**Comment by nitinmotgi** [comment]
Metric need to be centered between the two nodes.

**Comment by ajainarayanan** [comment]
:+1: LGTM

**Pull request merged**
