### PR TITLE
adds plugin icons for hydrator

### PR DESCRIPTION
**Pull request by astewes**
*  Adds custom icons for hydrator plugins

TODO:
- [x] Resolve conflicts between some of the character entities used in fonts.less (i.e., both icon-s3 and icon-publish are both using content: "\e90a";)

Source:
source

Transform:
transform

Sink:
sink

### CODE REVIEW

**Comment by nitinmotgi** [comment]
A lot of transform icons are missing.

**Comment by nitinmotgi** [comment]
oh! transform itself are missing.

**Comment by elfenheart** [comment]
more icons coming.... this is for other plugins in Hydrator-Plugins

**Comment by ajainarayanan** [comment]
:+1: LGTM. Verified it locally (myself & @elfenheart). We can merge this PR and update the new set icons in another PR.

**Comment by elfenheart** [comment]
:+1: LGTM

**Pull request merged**
