### PR TITLE
Use POST in RanksServiceHandler for better UI integration

### PR DESCRIPTION
**Pull request by rohitsinha54**
Build: http://builds.cask.co/browse/CDAP-RBT305-1

### CODE REVIEW

**Comment by henry-cask** [comment]
Why is it actually change to POST? To avoid the client cache?

**Comment by rohitsinha54** [comment]
@henry-cask : Earlier we were doing with query params which does not have support through our current UI. So we changed it to use POST as the data is an url which will have / etc.

**Comment by henry-cask** [comment]
+1

LGTM

**Comment by rohitsinha54** [comment]
Will merge as soon as the build passes.

**Comment by rohitsinha54** [comment]
Build : http://builds.cask.co/browse/CDAP-RBT305-2

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Pull request merged**
