### PR TITLE
CDAP-3066 fix FileBatchSource

### PR DESCRIPTION
**Pull request by jayfjin**
JIRA - https://issues.cask.co/browse/CDAP-3066
BUILD - http://builds.cask.co/browse/CDAP-DUT2289-1

Local variable aliased class variable blocking functionality.

### CODE REVIEW

**Comment by bdmogal** [comment]
The code fix is pretty innocuous. However, what was the failure? Is it possible to add a unit test?

**Comment by chtyim** [comment]
From the descriptions, seems like it's a bad choice of variable name?

**Comment by jayfjin** [comment]
Upon failure, the MapReduce should try to re-read in data. This does not happen. datesToRead is an accurate description of the variable, it denotes the dates that still need to be read in.

**Comment by anwar6953** [comment]
I think @chtyim 's point is that it gets its value from a field denoted by `LAST_TIME_READ`, which seems like a single value, whereas datesToRead seems like it has multiple values.

**Comment by jayfjin** [comment]
that's because datesToRead can have multiple values.

**Comment by anwar6953** [comment]
Also, `LAST_TIME_READ` denotes that it was already read/processed, but `datesToRead` denotes that it has yet to be processed.

**Comment by jayfjin** [comment]
datesToRead has yet to be processed upon read in from the table...

**Comment by anwar6953** [comment]
The confusion was that `LAST_TIME_READ` seems to contradict `datesToRead`, but it's fine because `LAST_TIME_READ` was the exclusive end-range of the previous run's range to read.

**Comment by anwar6953** [comment]
LGTM

**Pull request merged**
