### PR TITLE
CDAP-5461 revert temporary parquet plugin renames

### PR DESCRIPTION
**Pull request by albertshau**

### CODE REVIEW

**Comment by albertshau** [comment]
undoing most of https://github.com/caskdata/cdap/pull/5449

**Comment by anwar6953** [comment]
LGTM

**Comment by albertshau** [comment]
http://builds.cask.co/browse/CDAP-DOB172

**Comment by awholegunch** [comment]
LGTM: Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB172-1)

**Pull request merged**
