### PR TITLE
Feature/merge release 2.7.0

### PR DESCRIPTION
**Pull request by bdmogal**

### CODE REVIEW

**Comment by bdmogal** [comment]
@gokulavasan @anwar6953 Please review

**Comment by gokulavasan** [comment]
LGTM :+1: Resolved those two conflicts right? Other than that it should be ok.

**Comment by anwar6953** [comment]
Resolution of client-tests merge conflict LGTM.

**Comment by bdmogal** [comment]
Waiting for a build just in case - https://builds.cask.co/browse/CDAP-DUT617-1, since there were minor merge conflicts.

**Comment by bdmogal** [comment]
Build passed: https://builds.cask.co/browse/CDAP-DUT617-2
Merging

**Pull request merged**
