### PR TITLE
Make cdap depend on tephra 0.6.2

### PR DESCRIPTION
**Pull request by rohitsinha54**
Build: http://builds.cask.co/browse/CDAP-DUT2687-2

### CODE REVIEW

**Comment by chtyim** [comment]
LGTM

**Comment by poornachandra** [comment]
`data.tx.snapshot.codecs` needs to be updated in `cdap-default.xml` to include `SnapshotCodecV4`.

**Comment by rohitsinha54** [comment]
Tested on cluster with these changed. HBase98 coprocessor were picked up. Verified data consistency and clean logs after running flush, compact commands.

**Comment by rohitsinha54** [comment]
New build running with test fix: http://builds.cask.co/browse/CDAP-DUT2687-5

**Comment by rohitsinha54** [comment]
Random test failure. Giving it one more try here: http://builds.cask.co/browse/CDAP-DUT2687-6

**Comment by rohitsinha54** [comment]
Build failed again due to the hung issue. New build here: http://builds.cask.co/browse/CDAP-DUT2687-7

**Comment by rohitsinha54** [comment]
Build passed. Merging.

**Pull request merged**
