### PR TITLE
CDAP-1248 Categorized CLI commands and added SearchCommandsCommand

### PR DESCRIPTION
**Pull request by jwang47**
* Help output is categorized under "General", "Data Ingress", "Data Egress", or "Lifecycle"
* Help for all commands or only for a particular category: `help` or `help data_ingress`
* Search available commands using a regex: `search "start "`
  * If query doesn't start with `^`, then `^.*?` is added before the regex
  * If query doesn't end with `$`, then `.*?$` is added after the regex
  * This is to make searching more similar to most search engines, though this only supports exact substring matching, rather than keyword searching (didn't think keyword searching applied well here)

Sample usage:

```
cdap (http://localhost:10000)> help 
general    lifecycle    egress    ingest
cdap (http://localhost:10000)> help ingest

INGEST

  load stream <stream-id> <local-file-path> [<content-type>]
    Loads a file to a Stream. The content of the file will become multiple
    events in the stream, based on the content type. If <content-type> is not
    provided, it will be detected by the file extension

  send stream <stream-id> <stream-event>
    Sends an event to a Stream


cdap (http://localhost:10000)> search "start "

Listing matches for "start ":

LIFECYCLE

  start flow <app-id.flow-id> [<runtime-args>]
    Starts a Flow. <runtime-args> is specified in the format "key1=a key2=b"

  start mapreduce program <app-id.mapreduce-id> [<runtime-args>]
    Starts a MapReduce Program. <runtime-args> is specified in the format
    "key1=a key2=b"

  start procedure <app-id.procedure-id> [<runtime-args>]
    Starts a Procedure. <runtime-args> is specified in the format "key1=a
    key2=b"

  start service <app-id.service-id> [<runtime-args>]
    Starts a Service. <runtime-args> is specified in the format "key1=a key2=b"

  start spark program <app-id.spark-id> [<runtime-args>]
    Starts a Spark Program. <runtime-args> is specified in the format "key1=a
    key2=b"

  start workflow <app-id.workflow-id> [<runtime-args>]
    Starts a Workflow. <runtime-args> is specified in the format "key1=a key2=b"


cdap (http://localhost:10000)> help

CLI version 2.8.0-SNAPSHOT
CDAP_HOST=localhost

Available commands:

GENERAL

  connect <cdap-instance-uri>
    Connects to a CDAP instance.

  exit
    Exits the CLI

  help [<command-category>]
    Prints this helper text. Optionally provide <command-category> to get help
    with a specific category

  search <query>
    Searches available commands

  version
    Prints the version

LIFECYCLE

  create adapter <adapter-name> type <adapter-type> [props <adapter-props>]
                 src <adapter-source> [src-props <adapter-source-config>] sink
                 <adapter-sink> [sink-props <adapter-sink-config>]
    Creates a Adapter

  create dataset instance <dataset-type> <new-dataset-name>
    Creates a Dataset

  create stream <new-stream-id>
    Creates a Stream
  ...
```

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
This looks great. Suggest having following categories
`general`
`lifecycle` 
`ingest` 
`explore`
`egress`

**Comment by nitinmotgi** [comment]
Is there anyway to specify notes and examples for each command. More help on command can show that. Is that possible ?

**Comment by nitinmotgi** [comment]
@jwang47 also we should separate `dataset`

**Comment by nitinmotgi** [comment]
@jwang47 so I would say the whole list can be `general, lifecycle, ingest, dataset, explore, egress, operations`

**Comment by nitinmotgi** [comment]
@jwang47 also you remove `
CLI version 2.8.0-SNAPSHOT
CDAP_HOST=127.0.0.1

Available commands:
`

**Comment by nitinmotgi** [comment]
@jwang47 to exit / quit we should honor both `exit | quit`

**Comment by jwang47** [comment]
@sreevatsanraman Categories sound good

@nitinmotgi 

* Right now we don't have any more detailed notes or examples. We can add that later.
* Categories sound good to me, but what is `operations`?
* Yes, the redundant info from `help` can be removed, since both are accessible elsewhere.
* Yes, we can do both exit and quit

**Comment by awholegunch** [comment]
Some of the sentences ends with a period, some doesn't. "Creates a Adapter"; we should be able to have a function that returns the correct article ("a/an").

**Comment by sreevatsanraman** [comment]
@jwang47 - search is a good feature, but "search" keyword is confusing a bit. How about "command_search"

**Comment by sreevatsanraman** [comment]
Also we should surface cmd_search in the help option

**Comment by nitinmotgi** [comment]
lgtm :+1:

**Comment by jwang47** [comment]
@awholegunch Right, I'll fix that in another PR. Created JIRA issue here: https://issues.cask.co/browse/CDAP-1415
@sreevatsanraman How about "search commands <query>"?

**Comment by sreevatsanraman** [comment]
sounds good @jwang47

**Pull request merged**
