### PR TITLE
Feature/ui admin restructure

### PR DESCRIPTION
**Pull request by astewes**
* Restructures admin controller directory to match template directory structure
* Renames controllers to align with controller naming convention used across the UI

http://admin-restructure1834-1000.dev.continuuity.net:9999/

screen shot 2015-06-26 at 11 21 35 am 2
screen shot 2015-06-26 at 11 22 14 am 2

admin

### CODE REVIEW

**Comment by elfenheart** [comment]
@astewes Can you include the file structure tree of *feature > admin* in here so it's easier to review?

**Comment by elfenheart** [comment]
I see that you put preferences-ctrl under Namespace, I don't think this is correct. In Admin, that preference controller is being used under 3 instances: System, Namespace, and Application. Perhaps extract that out to global (same level as admin-ctrl and overview-ctrl). The template structure is correct though

**Comment by elfenheart** [comment]
:+1: LGTM

**Comment by ajainarayanan** [comment]
@astewes :

**Comment by ajainarayanan** [comment]
:+1: LGTM

**Pull request merged**
