### PR TITLE
CDAP-3449 Handle previous increment in all cases in readless increment co-processor

### PR DESCRIPTION
**Pull request by poornachandra**
JIRA - https://issues.cask.co/browse/CDAP-3449

Porting changes from https://github.com/caskdata/cdap/pull/3645 to 3.0 branch.

### CODE REVIEW

**Comment by henry-cask** [comment]
Any particular change different from #3645 ?

**Comment by poornachandra** [comment]
HBase 94 changes are new.

**Comment by poornachandra** [comment]
Build http://builds.cask.co/browse/CDAP-RB300-7

**Comment by henry-cask** [comment]
LGTM for 0.94

**Comment by poornachandra** [comment]
Build passed, commits squashed.

**Pull request merged**
