### PR TITLE
Introducing Checkpoint class to represent checkpoints

### PR DESCRIPTION
**Pull request by poornachandra**
Also contains minor refactoring in https://github.com/caskdata/cdap/commit/b7ed0b8a8ed604abc97d00319318ee01ae2aa7f9. It may be easier to review the commits separately.

JIRA https://issues.cask.co/browse/CDAP-2053

### CODE REVIEW

**Comment by poornachandra** [comment]
Build http://builds.cask.co/browse/CDAP-DUT1573-2

**Comment by poornachandra** [comment]
Build http://builds.cask.co/browse/CDAP-DUT1573-3

**Comment by sreevatsanraman** [comment]
one very minor comment. fix and merge when the build passes.

LGTM :+1:

**Comment by poornachandra** [comment]
Build http://builds.cask.co/browse/CDAP-DUT1573-4

**Pull request merged**
