### PR TITLE
Remove shell scripts from maven archetypes.

### PR DESCRIPTION
**Pull request by anwar6953**
Remove shell scripts from maven archetypes.

https://issues.cask.co/browse/CDAP-4243
http://builds.cask.co/browse/CDAP-DUT3146-2

### CODE REVIEW

**Comment by awholegunch** [comment]
Can the CLI handle injecting data? If so, we can change the examples and then remove that script.

**Comment by anwar6953** [comment]
Removed the scripts for:
Purchase, SparkKMeans, SparkPageRank, WebAnalytics

**Comment by awholegunch** [comment]
I've removed the example from the stream documentation. I will add something to the RESTful API docs as an example.

**Comment by awholegunch** [comment]
Docs LGTM.

**Comment by bdmogal** [comment]
LGTM

**Pull request merged**
