### PR TITLE
Feature/ui merge schema propagation PRs

### PR DESCRIPTION
**Pull request by ajainarayanan**
Merge of PRs : [4913](https://github.com/caskdata/cdap/pull/4913) + [4922](https://github.com/caskdata/cdap/pull/4922).

In addition have fixed the following issues:
- Fixes merge conflict between branches.
- Fixes ```clf``` & ```syslog``` formats (to not include schema while sending to backend).
- Hides propagate & clear buttons from output schema when ```avro``` format is chosen in Stream source.

### CODE REVIEW

**Comment by ajainarayanan** [comment]
Testing this on cluster.

**Comment by elfenheart** [comment]
ts is type long, headers type map<string, string>

**Comment by ajainarayanan** [comment]
:+1: LGTM. Waiting for test in cluster.

**Comment by elfenheart** [comment]
:+1: LGTM

**Pull request merged**
