### PR TITLE
Feature/cdap 3498 upgrade twill

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by albertshau** [comment]
lgtm

**Comment by anwar6953** [comment]
Marking On-hold, so this doesn't get merged.
This should have a green build of integration tests first (its currently failing).

**Comment by chtyim** [comment]
It has to get merge before integration can be green, which the hydrator app needs twill-0.7.0 and the cdap snapshot compiled with twill-0.7.0

**Comment by chtyim** [comment]
Associated Hydrator PR. https://github.com/caskdata/hydrator-plugins/pull/127

**Comment by anwar6953** [comment]
Integration tests all passed, except on HDP 2.2. I manually ran the test cases that failed there, and they passed during the manual run.

**Pull request merged**
