### PR TITLE
(CDAP-4234) Fix HttpContentConsumer concurrent context issue

### PR DESCRIPTION
**Pull request by chtyim**
This PR contains two commits for easy review.

First commit is just refactoring:
    (CDAP-4234) Refactor ServiceHttpService to use LoadingCache to simplify logic.
    - Instead of maintaining WeakReference and ReferenceQueue manually, use a LoadingCache to help

Second commit is the actual fix:
    (CDAP-4234) Fix HttpContentConsumer concurrent context issue
    - Make sure the same context/handler pair won’t get concurrent access from multiple threads
    - A given context/handler pair can be reused by different threads

### CODE REVIEW

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DUT3144-3

**Comment by chtyim** [comment]
Yes and it was like that before. One improvement we can make is in the cleanUp() method, we also loop through all entries in the LoadingCache and invalid those Threads that are no longer alive.

**Comment by anew** [comment]
@chtyim I made some comments on the commits themselves. Two major questions:
- can responder.execute() throw? in that case, cancelling the context needs to be inside a finally
- should we attempt to minimize the size of the context pair queue per thread?

Other than that, very clean code and great to review because of the useful comments.

**Comment by chtyim** [comment]
@anew Addressed/responded to your comments. Please have a look.

**Comment by anew** [comment]
Thanks for the discussion. I am not 100% convinced by how the size of the queues is bounded. Would it be hard to emit a system metric for that, so that we can monitor it under real workloads? 

Other than that LGTM

**Comment by chtyim** [comment]
Added a queue size metrics.

**Comment by chtyim** [comment]
Building in http://builds.cask.co/browse/CDAP-DUT3263-1

**Comment by anew** [comment]
So the metric will have the number of contexts that are in the queue, that is, that are not in use. Right?

**Comment by chtyim** [comment]
Yes, the metrics only tracks the pool size, which are the "inactive" contexts.

**Comment by anew** [comment]
LGTM

**Comment by chtyim** [comment]
Squashed commits. Waiting for build.

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DUT3263-5

**Pull request merged**
