### PR TITLE
Twitter rtCount, check empty/null for KafkaSource format

### PR DESCRIPTION
**Pull request by gokulavasan**

### CODE REVIEW

**Comment by anwar6953** [comment]
Should this also be a check for empty string?
https://github.com/caskdata/cdap/pull/3463/files#diff-1ab489e685b8a3ae250a715f02a29308R135

**Comment by gokulavasan** [comment]
@anwar6953 Addressed your comment

**Comment by hsaputra** [comment]
LGTM

**Comment by anwar6953** [comment]
lgtm

**Pull request merged**
