### PR TITLE
CDAP-1795: Cleanup CLIMain construction

### PR DESCRIPTION
**Pull request by jwang47**

### CODE REVIEW

**Comment by jwang47** [comment]
http://builds.cask.co/browse/CDAP-DUT975

**Comment by jwang47** [comment]
Build passed http://builds.cask.co/browse/CDAP-DUT975-2

**Comment by jwang47** [comment]
Build passed http://builds.cask.co/browse/CDAP-DUT975-3

**Comment by jwang47** [comment]
This is not required for 3.0, so moving it out.

**Comment by jwang47** [comment]
This fixes https://issues.cask.co/browse/CDAP-1795, so moving back into 2.8.

**Comment by ParthGandhi** [comment]
:+1:

**Pull request merged**
