### PR TITLE
Rename date field to request_time field for CLF

### PR DESCRIPTION
**Pull request by sreevatsanraman**
* JIRA: https://issues.cask.co/browse/CDAP-5629
* Build: http://builds.cask.co/browse/CDAP-DUT4003

* Test on Hive 1.2 passes.

### CODE REVIEW

**Comment by poornachandra** [comment]
LGTM after tests.

**Comment by chtyim** [comment]
So this change is not backward compatible?

**Comment by chtyim** [comment]
Pressed wrong button

**Comment by sreevatsanraman** [comment]
This is set in explore schema - when the explore schema changes the external table is recreated.

**Comment by chtyim** [comment]
LGTM

**Comment by poornachandra** [comment]
LGTM for https://github.com/caskdata/cdap/pull/5606/commits/3168db47ba6ee861085a0a943074f3b41ab0e2b3

**Comment by sreevatsanraman** [comment]
Build passed. Merging.

**Pull request merged**
