### PR TITLE
CDAP-2956 Switching to configurer style API for WorkflowAction

### PR DESCRIPTION
**Pull request by gokulavasan**
Build : http://builds.cask.co/browse/CDAP-DUT2705

JIRA : https://issues.cask.co/browse/CDAP-2956

### CODE REVIEW

**Comment by albertshau** [comment]
Are there any docs or examples that need to be changed along with this?  If not, lgtm

**Comment by gokulavasan** [comment]
@albertshau The tests are failing in bamboo. So there might be additional changes to fix them. Will remove the on-hold tag and tag you once the PR is ready for review. Thanks!

**Comment by gokulavasan** [comment]
@albertshau Bamboo build passed. Please review. I will open separate PR to change docs and examples.

**Comment by albertshau** [comment]
:+1:

**Comment by anew** [comment]
I do not understand the new API. 

We have a configure(WorkflowActionConfigurer) that calls the old configure() method. If a subcass overrides it, then it has to use configurer.setName()/setDescription() etc. If a subclass does not override it, then when should it call the new setName()/setDescription() of this class? Calling it in configure() will have no effect, because that has to return a spec, which is used to give the name, description etc.  So the new set methods are not useful for anything? 

Also, why do we deprecate getName/Description() and document that setName/Description() should be used instead. This whole change makes little sense to me. I would like to see an example of how it is supposed to be used.

**Pull request merged**
