### PR TITLE
Remove deprecated documentation, text and images

### PR DESCRIPTION
**Pull request by awholegunch**
This removes deprecated documentation (https://issues.cask.co/browse/CDAP-1987, https://issues.cask.co/browse/CDAP-2002):

- Removes Procedures, in all references
- Removes the RESTful API v2, except for one reference ([Querying Multiple Metrics](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_Remove_deprecated_docs/en/reference-manual/http-restful-api/metrics.html#querying-for-multiple-metrics)); that is to fixed in 3.0 but AFAIK, hasn't as of yet.
- Adds a sample ``curl`` call for querying multiple metrics; tested against 3.0.0-SNAPSHOT.
- Removes out-dated console images that were not being used anywhere. It retains images that are being used that require updating; they will be handled by another PR, being tracked by other issues.

It also sets up the [Release Notes for 3.0](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_Remove_deprecated_docs/en/reference-manual/release-notes.html).
It re-orders the Reference Manual Table of Contents to be more-or-less alphabetical; the most general item ("Supported Characters") is on top, with everything alphabetical below. See the
[Reference Manual Index Page](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_Remove_deprecated_docs/en/reference-manual/index.html).

This is staged at: http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_Remove_deprecated_docs/en/index.html

Pages of note:
- [Reference Manual](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_Remove_deprecated_docs/en/reference-manual/index.html)
- [RESTful APIs](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_Remove_deprecated_docs/en/reference-manual/http-restful-api/index.html)
- [Multiple Metrics](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_Remove_deprecated_docs/en/reference-manual/http-restful-api/metrics.html#querying-for-multiple-metrics)

### CODE REVIEW

**Comment by awholegunch** [comment]
There are numerous references in other repos that need to be cleaned up. I will make a list and add them here. After I make another cup of coffee...

**Comment by awholegunch** [comment]
Here are related PRs that also require reviewing and merging:
- https://github.com/cdap-guides/cdap-twitter-ingest-guide/pull/14
- https://github.com/cdap-guides/cdap-timeseries-guide/pull/15
- https://github.com/cdap-guides/cdap-spark-guide/pull/40
- https://github.com/cdap-guides/cdap-mapreduce-guide/pull/16
- https://github.com/cdap-guides/cdap-bi-guide/pull/29
- https://github.com/cdap-guides/cdap-flume-guide/pull/20
- https://github.com/cdap-guides/cdap-flow-guide/pull/16

**Comment by sreevatsanraman** [comment]
LGTM :+1:

**Comment by awholegunch** [comment]
Waiting for other repos (listed above) to be reviewed and merged first.

**Comment by awholegunch** [comment]
I've reviewed the includes of these other repos, and this looks good to go.

**Pull request merged**
