### PR TITLE
CDAP-3173 Add fastutil classes to transaction co-processor jar

### PR DESCRIPTION
**Pull request by poornachandra**
JIRA https://issues.cask.co/browse/CDAP-3173

### CODE REVIEW

**Comment by poornachandra** [comment]
Build - http://builds.cask.co/browse/CDAP-RBT401-1

**Comment by sreevatsanraman** [comment]
LGTM. Merge if it is tested on a cluster.

**Comment by ghelmling** [comment]
+1

**Comment by poornachandra** [comment]
Build http://builds.cask.co/browse/CDAP-RBT401-3 is green

**Pull request merged**
