### PR TITLE
CDAP-1174 Namespace start script functions

### PR DESCRIPTION
**Pull request by wolf31o2**
Same as #4689 against release/3.3 branch. Getting rid of some tech debt by prepending cdap to most function names.

### CODE REVIEW

**Comment by anwar6953** [comment]
There was a comment by @dereklwood on https://github.com/caskdata/cdap/pull/4689, that this change should not be on develop branch. Based off that, should this change not even be merged to release branch, since we merge release into develop periodically?

**Comment by sreevatsanraman** [comment]
@anwar6953 - the PR you mentioned was closed because we wanted to open this against 3.3 after feature freeze.

**Comment by sreevatsanraman** [comment]
@wolf31o2 - can you resolve the conflicts, so that we can review.

**Comment by wolf31o2** [comment]
Will do.

**Comment by wolf31o2** [comment]
Conflicts are resolved. This needs to be reviewed/merged as #4823 uses these changes and shouldn't have been merged until after this was approved. The lines of code in question aren't likely to change, but still...

**Comment by sreevatsanraman** [comment]
lgtm

**Pull request merged**
