### PR TITLE
removing elastic search plugins since they were moved to the

### PR DESCRIPTION
**Pull request by albertshau**
cdap-plugins repo

### CODE REVIEW

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by awholegunch** [comment]
LGTM. The only concerns I have are: we don't have anything that links to the "new" location; some of the info in the docs, such as details on how it works, the need to be running the server before the app is created—though maybe that really meant uploaded—haven't been captured in the other repo.

**Comment by albertshau** [comment]
o we should update the other repo if it is missing documentation that is present here

**Comment by awholegunch** [comment]
https://issues.cask.co/browse/CDAP-3800 has been created to do that later.

**Comment by albertshau** [comment]
thanks, will merge this then

**Comment by albertshau** [comment]
after build http://builds.cask.co/browse/CDAP-RBT486

**Comment by albertshau** [comment]
build green, merging

**Pull request merged**
