### PR TITLE
Add background formatting to literals, but not when they are in a table.

### PR DESCRIPTION
**Pull request by awholegunch**
This is a simple CSS change that adds a ``background box with a border`` to the documentation's literals, similar to ``this text`` in GitHub. The style is a little stronger, as it has a border in addition to the background coloring.

It does not do it when the text is in a table, as that doesn't work very well.

Some editing might be required, as text such ``"sample"`` no longer requires the quotes to distinguish it, and can instead just be ``sample``. As can be seen in the [Hello World example](http://builds.cask.co/artifact/CDAP-DOB152/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/examples-manual/examples/hello-world.html), some of the titles have literals in them; the literals can either be removed or suppressed.

Passes [Quick Build 2](http://builds.cask.co/browse/CDAP-DOB152-2)
*Build 2 implements @poornachandra's suggestion: no border, slightly darker background.*

Sample Pages:
- [Quick Start](http://builds.cask.co/artifact/CDAP-DOB152/shared/build-2/Docs-HTML/3.4.0-SNAPSHOT/en/developers-manual/getting-started/quick-start.html)
- [Lifecycle RESTful API](http://builds.cask.co/artifact/CDAP-DOB152/shared/build-2/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/http-restful-api/lifecycle.html)
- [Hello World example](http://builds.cask.co/artifact/CDAP-DOB152/shared/build-2/Docs-HTML/3.4.0-SNAPSHOT/en/examples-manual/examples/hello-world.html)

### CODE REVIEW

**Comment by poornachandra** [comment]
I think the border around the literal text makes it look a bit patchy. How about removing the border? We can then notice the literal while reading the text, and the text doesn't look broken. Sample text below -

screen shot 2016-03-17 at 6 55 24 pm

**Comment by elfenheart** [comment]
@awholegunch the UI screenshots in the quick start seems to be the super old UI. Should we update?

**Comment by awholegunch** [comment]
@elfenheart We should. I will put together a list of required screenshots.

**Comment by sreevatsanraman** [comment]
LGTM

**Pull request merged**
