### PR TITLE
(CDAP-1539) Fix MR not to write to /tmp directory, but to container local

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by anew** [comment]
Terence, will this fix the issue, or just move the spill to a different directory? The original problem was that files in /tmp were created but not cleaned up. This does not seem to fix the cleanup?

**Comment by chtyim** [comment]
It is intentionally like this because there is no clear hook on doing the cleanup when the MR is completed (the folder is needed as long as there is need to load class from the ProgramClassLoader). Instead, if we keep the tmp folder inside the container folder, Yarn will do the cleanup.

**Comment by anew** [comment]
OK. LGTM

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DUT826-1

**Pull request merged**
