### PR TITLE
[CDAP-5006] Tracker Main Page + Search Results

### PR DESCRIPTION
**Pull request by elfenheart**
Missing:
- Metadata Filter
- Jump button functionality
- Real data for Description, Create Date, Query Found

### CODE REVIEW

**Comment by astewes** [comment]
:+1: LGTM

**Comment by BradyAjay** [comment]
a few things:
- all filters should be selected by default
- "show all" should appear over numbers to right
- No results message should read: “No results match your filter settings."

**Comment by elfenheart** [comment]
Adressed comments

**Comment by elfenheart** [comment]
demoed to Nitin

**Pull request merged**
