### PR TITLE
remove support for procedures

### PR DESCRIPTION
**Pull request by anew**
https://issues.cask.co/browse/CDAP-2126
Also: 
- replace with services where needed in tests
- fix failing tests

### CODE REVIEW

**Comment by anew** [comment]
this is not ready for review yet

**Comment by anew** [comment]
I ran all tests manually that where affected. 
Bamboo build also succeeded. http://builds.cask.co/browse/CDAP-DUT1477

**Comment by chtyim** [comment]
LGTM

**Comment by anew** [comment]
I want to merge, but there is one problem. I found out that IntelliJ did not update the copyright in any of the files I changed. They are all still 2014, but should be 2014-2015. I don't what changed in IntelliJ, it used to update that automatically for me. I will figure that out and then merge.

**Pull request merged**
