### PR TITLE
[CDAP-4894] make coprocessor jar locations path-only instead of full URIs

### PR DESCRIPTION
**Pull request by anew**
Jira: https://issues.cask.co/browse/CDAP-4894
Tested on a secure cluster.

### CODE REVIEW

**Comment by chtyim** [comment]
LGTM

**Comment by anwar6953** [comment]
Will this need an upgrade to handle places where full URIs were written?

**Comment by anew** [comment]
@anwar6953: yes, this will happen as part of the regular upgrade tool. It updates all the coprocessors and will rely on the same abstract class for that. This is a good example for nice code: all places that configure HBase coprocessors in CDAP share this code.

**Comment by chtyim** [comment]
LGTM

**Pull request merged**
