### PR TITLE
CDAP-4355 Change 'explore.enabled' to 'true' by default

### PR DESCRIPTION
**Pull request by anwar6953**
https://issues.cask.co/browse/CDAP-4355

TODO:
- Relevant changes to CSD and Ambari.
- Test on cluster

### CODE REVIEW

**Comment by awholegunch** [comment]
Doc changes LGTM, though there is another PR (https://github.com/caskdata/cdap/pull/4727) that will need to accommodate this…

**Comment by awholegunch** [comment]
I just noticed that you deleted the file ``cdap-docs/admin-manual/source/_images/ambari/ss07-config-enable-explore.png`` yet still referred to it. I would suggest leaving the file in, as it shows how the properties relate to the UI.

**Comment by anwar6953** [comment]
Updated to keep the png file.

**Comment by anew** [comment]
Code changes are LGTM

**Pull request merged**
