### PR TITLE
Removed deprecated classes RuntimeStats and ConfigurableTestBase. Mov…

### PR DESCRIPTION
**Pull request by bdmogal**
…ed all functionality from ConfigurableTestBase to TestBase. Moved MetricsManager to cdap-test (where all the other test manager classes are located) from cdap-unit-test.

### CODE REVIEW

**Comment by bdmogal** [comment]
http://builds.cask.co/browse/CDAP-DUT3187-1

**Comment by anwar6953** [comment]
Other test manager classes are in 'cdap-test', because they are used in both 'cdap-unit-test' and 'cdap-integration-test'.
However, MetricsManager is only a unit-test implementation, right?

**Comment by bdmogal** [comment]
shouldn't we extend MetricsManager to support integration-test as well?

**Comment by anwar6953** [comment]
There exists a Remote implementation of RuntimeMetrics, which can be used from integration tests.
No need to have another class for metrics, right?

**Comment by bdmogal** [comment]
But shouldn't all tests have a standard way of accessing metrics?

**Comment by anwar6953** [comment]
Opened JIRA for this - https://issues.cask.co/browse/CDAP-4302
Remainder LGTM

**Comment by bdmogal** [comment]
Build passed - http://builds.cask.co/browse/CDAP-DUT3187-1. Merging.

**Pull request merged**
