### PR TITLE
Updated the entity-type parameter description for the lineage rest api call.

### PR DESCRIPTION
**Pull request by sagarkapare**

### CODE REVIEW

**Comment by awholegunch** [comment]
Is there an Issue for this? Do any examples use this or show this that need updating?

**Comment by sagarkapare** [comment]
I verified that other occurrences of the `entity-type` in that rst are fine. I could not find any other places where the update needed but @bdmogal can confirm it. There is no JIRA for it since it was small change.

**Comment by bdmogal** [comment]
oh these are just containers in the REST API. LGTM. This is just a typo.

**Comment by bdmogal** [comment]
Shouldn't need any other updates.

**Comment by sagarkapare** [comment]
Thanks @bdmogal @awholegunch for taking look. Merging.

**Pull request merged**
