### PR TITLE
CDAP-2346 status endpoint should return json

### PR DESCRIPTION
**Pull request by gokulavasan**
JIRA : https://issues.cask.co/browse/CDAP-2346

### CODE REVIEW

**Comment by anwar6953** [comment]
LGTM

**Comment by gokulavasan** [comment]
Build : http://builds.cask.co/browse/CDAP-RBT239-2

**Comment by anwar6953** [comment]
LGTM

**Comment by gokulavasan** [comment]
Build passed : http://builds.cask.co/browse/CDAP-RBT239-3

**Comment by anwar6953** [comment]
:+1:

**Pull request merged**
