### PR TITLE
Remove SNAPSHOT from version

### PR DESCRIPTION
**Pull request by bdmogal**

### CODE REVIEW

**Comment by wolf31o2** [comment]
:+1: LGTM

**Comment by sreevatsanraman** [comment]
There are more places. Don't merge yet.

**Comment by sreevatsanraman** [comment]
```
ind . -name '*' -type f | xargs grep "3.2.0-SNAPSHOT"   | grep -v target  | grep -v binary
./cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>3.2.0-SNAPSHOT</cdap.version>
./cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>3.2.0-SNAPSHOT</cdap.version>
./cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>3.2.0-SNAPSHOT</cdap.version>
./cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>3.2.0-SNAPSHOT</cdap.version>
./cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>3.2.0-SNAPSHOT</cdap.version>
./cdap-archetypes/cdap-app-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>3.2.0-SNAPSHOT</cdap.version>
./cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>3.2.0-SNAPSHOT</cdap.version>
./cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/pom.xml:    <cdap.version>3.2.0-SNAPSHOT</cdap.version>
./cdap-docs/developers-manual/source/building-blocks/artifacts.rst:The suffix can be any of the acceptable characters. For example, '3.2.0-SNAPSHOT' is a valid artifact version,
./cdap-docs/reference-manual/source/http-restful-api/artifact.rst:          "version": "3.2.0-SNAPSHOT"
./cdap-examples/resources/weblog-analytics-config.json:        "version": "3.2.0-SNAPSHOT"
./cdap-examples/resources/weblog-analytics.txt:create app test cdap-etl-batch 3.2.0-SNAPSHOT system \$CDAP_HOME/examples/resources/weblog-analytics-config.json 
./cdap-ui/templates/apps/predefined/AmazonSQSToHBase.json:    "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/CassandraToHBaseAndHDFS.json:    "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/DatabaseToCassandra.json:        "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/ETLIntoElasticSearch.json:        "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/HBaseToCassandra.json:    "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/KafkaToCassandra.json:        "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/KafkaToCassandraAndCDAPStream.json:        "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/KafkaToElasticsearch.json:    "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/KafkaToHBase.json:        "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/KafkaToOLAPCube.json:    "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/KafkaToStream.json:    "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/StreamToHBase.json:        "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/TwitterToHBase.json:        "version": "3.2.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/TwitterToStream.json:    "version": "3.2.0-SNAPSHOT"

```

**Comment by albertshau** [comment]
cdap-docs/reference-manual/source/http-restful-api/artifact.rst should be changed to use `|version|` but cdap-docs/developers-manual/source/building-blocks/artifacts.rst does not need to change, since it's being used as an example of a snapshot version

**Comment by bdmogal** [comment]
```
$ grep -ri "3.2.0-SNAPSHOT" *
cdap-docs/developers-manual/source/building-blocks/artifacts.rst:22:The suffix can be any of the acceptable characters. For example, '3.2.0-SNAPSHOT' is a valid artifact version,
```

**Comment by albertshau** [comment]
one comment, otherwise lgtm

**Comment by albertshau** [comment]
one comment, then good to merge

**Comment by albertshau** [comment]
:+1:

**Comment by bdmogal** [comment]
Squashed commits. Merging.

**Pull request merged**
