### PR TITLE
Give PurchaseHistoryBuilder (driver of the MR job) more memory.

### PR DESCRIPTION
**Pull request by anwar6953**
Running on HDP 2.3, the PurchaseHistoryWorkflow kept restarting because it went over its memory limits. Increasing the MR driver resources to 1024 (default is 512) works around the issue.

Related PR which made this possible: https://github.com/caskdata/cdap/pull/4488

http://builds.cask.co/browse/CDAP-DUT3106-2

### CODE REVIEW

**Comment by bdmogal** [comment]
:+1:

**Comment by anwar6953** [comment]
@chtyim Should we make the default for all MapReduce driver be 1024m, instead of just for this MapReduce?

**Comment by awholegunch** [comment]
-1: You should change the docs for this...let me get you a note.

**Comment by awholegunch** [comment]
This page will need changing: http://docs.cask.co/cdap/3.3.0-SNAPSHOT/en/examples-manual/examples/purchase.html

**Comment by awholegunch** [comment]
And the MD5 hash...

**Comment by anwar6953** [comment]
Thanks for the headsup. Will update.

**Comment by anwar6953** [comment]
Done and pushed.

**Comment by awholegunch** [comment]
LGTM

**Comment by anwar6953** [comment]
Build failed, due to a flaky test that's on develop: https://issues.cask.co/browse/CDAP-4210
I've assigned the JIRA to myself, and currently looking at it.

Merging the PR, to unblock/fix integration test failures.

**Pull request merged**
