### PR TITLE
(CDAP-648) Add wait for service status check to ServiceManager

### PR DESCRIPTION
**Pull request by ParthGandhi**

### CODE REVIEW

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by anwar6953** [comment]
Replace a couple of instances of `serviceStatusCheck` with the implementation in ServiceManager.
For instance:
`WordCountTest.java`
`SparkPageRankAppTest.java`
`SparkKMeansAppTest.java`
`PurchaseAppTest`
`HelloWorldTest.java`
`TestMapReduceServiceIntegration.java`
`SparkKMeansAppTest.java` (in the spark-scala-archetype)
`SparkPageRankAppTest.java` (in the spark-scala-archetype)
`HelloWorldTest.java` (in cdap-app-archetype)

**Comment by anwar6953** [comment]
LGTM

**Comment by ParthGandhi** [comment]
@anwar6953 Good catch. Thanks!

**Comment by ParthGandhi** [comment]
https://builds.cask.co/browse/CDAP-DUT548-4

One test failed that was already failing on develop. Merging.

**Pull request merged**
