### PR TITLE
CDAP-3855 remove leftover adapter code

### PR DESCRIPTION
**Pull request by albertshau**
Adapters were removed in 3.2, but some of the code remained in
order to support upgrade from 3.1 to 3.2. Removing the leftover
code and removing code that was missed in the first round of
adapter removal.

### CODE REVIEW

**Comment by albertshau** [comment]
http://builds.cask.co/browse/CDAP-DUT3490

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by anwar6953** [comment]
This can be removed right:
https://github.com/caskdata/cdap/blob/feature/CDAP-3855-remove-adapter-leftovers/cdap-common/src/main/java/co/cask/cdap/common/logging/ApplicationLoggingContext.java#L40-40

**Comment by albertshau** [comment]
ah forgot about the logging stuff, will take a look at it

**Comment by anwar6953** [comment]
few instances of 'adapter' in this file:
https://github.com/caskdata/cdap/blob/feature/CDAP-3855-remove-adapter-leftovers/cdap-data-fabric/src/test/java/co/cask/cdap/data2/registry/UsageDatasetTest.java#L139-139

https://github.com/caskdata/cdap/blob/feature/CDAP-3855-remove-adapter-leftovers/cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/UsageHandlerTest.java#L254-254

image

**Comment by anwar6953** [comment]
Hey Albert. I just removed it from a few more places; can you take a look?
I'm unsure about my javadoc change in ReflectionUtils (specifically, whether that statement is still true or not).

**Comment by anwar6953** [comment]
LGTM otherwise!

**Comment by anwar6953** [comment]
Your changes LGTM.
If my commits are good, feel free to squash them.

**Comment by albertshau** [comment]
squashed commits

**Pull request merged**
