### PR TITLE
Remove old ACLTable code

### PR DESCRIPTION
**Pull request by jwang47**

### CODE REVIEW

**Comment by jwang47** [comment]
http://builds.cask.co/browse/CDAP-DUT794-1

**Comment by anew** [comment]
Will this require any upgrade procedure? In existing installations the ACLTableModule will be deployed in the dataset manager. If we remove the code, should we also add a step in the upgrade procedure to delete that module?

**Comment by jwang47** [comment]
Yes we should delete the module in the upgrade procedure. Where should I add the deletion code?

**Comment by anew** [comment]
Best talk to @bdmogal and @rohitsinha54

**Comment by jwang47** [comment]
Created issue to track the upgrade concerns https://issues.cask.co/browse/CDAP-1541

**Comment by jwang47** [comment]
http://builds.cask.co/browse/CDAP-DUT794-2

**Pull request merged**
