### PR TITLE
Add @Beta annotation and make final to RestartServiceInstancesStatus class.

### PR DESCRIPTION
**Pull request by henry-cask**
Tagged the RestartServiceInstancesStatus class as Beta and add final modifier to make sure
it is not inherited.

This class may change in the near future to support more hollistic history of system
services statuses.

### CODE REVIEW

**Comment by chtyim** [comment]
Proto is internal class, right? Do we need @Beta?

**Comment by henry-cask** [comment]
We have couple in proto like AdapterDetail and AdapterConfig.

**Comment by henry-cask** [comment]
Proto is internal to people developing CDAP so assuming people fork CDAP and start developing on top of CDAP, the @Beta annotation could help indicate this could change in near future.

**Comment by chtyim** [comment]
I don't object it, but at the same time, it means a lot of internal APIs need to have @Beta :)

**Comment by henry-cask** [comment]
Yeah, I personally think we should never add @Beta for release product =P
The original idea is that this class may evolve pretty soon, so @Beta is added to give heads up.

I would leave this open until tonight. 
If @anew is ok we DO NOT add @Beta annotation for this class, I will just close this PR as will not fix.

**Comment by albertshau** [comment]
proto is accessible in unit test so it's kind of public in a sense

**Comment by anew** [comment]
proto is not internal because it represents our REST API. Agreed that the serialized/jsonized proto objects won't have the @Beta, so I am ok with not having it there. But we should have some other way of indicating for a REST API that it is experimental.

**Comment by henry-cask** [comment]
Closing it for now.

**Pull request closed without merging**
