### PR TITLE
Set Adpater Worker resources before starting the program

### PR DESCRIPTION
**Pull request by gokulavasan**
Use ProgramOptions (system arguments) to pass instances, resources. Unfortunately this has to be replicated thrice in different places. Need to fix this cleanly in the future.

Bamboo: http://builds.cask.co/browse/CDAP-DUT1476-2

### CODE REVIEW

**Comment by albertshau** [comment]
won't different adapters clobber each other this way?

**Comment by gokulavasan** [comment]
Ok will address CDAP-2146 in this PR.

**Comment by gokulavasan** [comment]
@albertshau Addressed your comment. Please review.

**Comment by albertshau** [comment]
:+1:

**Pull request merged**
