### PR TITLE
fixes studio left panel height/positioning issues

### PR DESCRIPTION
**Pull request by astewes**
*  Reduces top offset of maximized bottom panel so that it occupies viewport up to the global navbar
*  Fixes margins of left panel top section buttons so that they're aligned evenly when left panel is both expanded and collapsed
*  Removes Pipelines button from data/apps section of dev start

Maximized bottom panel: 
buttons

Left panel expanding and collapsing:
leftpanel

Even margins of top panel buttons when expanded:
screen shot 2016-04-22 at 11 33 12 am

Pipelines button removed:
screen shot 2016-04-22 at 11 39 44 am

### CODE REVIEW

**Comment by ajainarayanan** [comment]
Talked to @astewes 
- We have shadow on the top when the bottom panel is maximized.
- We have a 1-2px gap in the post run actions in left actions list.

**Comment by ajainarayanan** [comment]
@astewes Added fixes for the following,
- Fixed the issue of going to old hydrator studio view when a pipeline is saved as draft.
- Fixed the issue of retaining the bottom panel setting when the maximized in detailed view. We seem to switch back to expanded view on switching tabs in maximized view.

**Comment by elfenheart** [comment]
👍 LGTM

**Comment by elfenheart** [comment]
👍  LGTM

**Pull request merged**
