### PR TITLE
CDAP-3583 CDAP-3521 Add app, program and data metadata while recording access

### PR DESCRIPTION
**Pull request by poornachandra**
Also add REST endpoint to retrieve metadata for a run.

### CODE REVIEW

**Comment by poornachandra** [comment]
Build - http://builds.cask.co/browse/CDAP-DUT2846-4

**Comment by anew** [comment]
Overall this looks good. 

One general remark: Why do some methods go through the LineageService, and some access the LineageStore directly. What is the purpose of LineageService? And why is it called a service when it does not implement Service?

**Comment by poornachandra** [comment]
LineageService needs a bit of re-factoring. That class is intended to be used only for lineage computation, and I'll be calling it LineageGenerator. All other straightforward lookups from lineage dataset will directly go to LineageStore.

Filed JIRA https://issues.cask.co/browse/CDAP-3659 for this.

**Comment by poornachandra** [comment]
@anew Thanks for the review. Other than the refactoring of LineageService, is the PR good to merge?

**Comment by anew** [comment]
Yes, other than that LGTM - didn't I mention that? :)

**Comment by poornachandra** [comment]
Thanks! Build is green, merging.

**Pull request merged**
