### PR TITLE
Deprecate Java 6.

### PR DESCRIPTION
**Pull request by awholegunch**
Staged at: [Release Notes: Deprecated and Removed Features](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-r3.0_release_notes_v2/en/reference-manual/release-notes.html#deprecated-and-removed-features)

### CODE REVIEW

**Comment by wolf31o2** [comment]
:+1: LGTM

**Comment by awholegunch** [comment]
I want to add the new ETL guides in, now that they are done. Putting this PR on hold until I get them in there.

**Comment by awholegunch** [comment]
I've added a link to the new guides: 
- [Guides page](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-r3.0_release_notes_v2/en/examples-manual/how-to-guides/index.html)
- [ETL Pipelines](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-r3.0_release_notes_v2/en/examples-manual/how-to-guides/cdap-etl-adapter-guide.html)

**Comment by awholegunch** [comment]
I haven't changed any code here, but I change the formatting of the [ETL Pipeline Guide](https://github.com/cdap-guides/cdap-etl-adapter-guide/blob/release/cdap-3.0-compatible/README.rst) to tone down the links. The results can be seen where [the Guide is included](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-r3.0_release_notes_v2/en/examples-manual/how-to-guides/cdap-etl-adapter-guide.html) in the CDAP Docs.

**Comment by bdmogal** [comment]
:+1:

**Pull request merged**
