### PR TITLE
For twill version, use 0.7.0-incubating-SNAPSHOT

### PR DESCRIPTION
**Pull request by anwar6953**
http://builds.cask.co/browse/CDAP-DUT3299-1

### CODE REVIEW

**Comment by chtyim** [comment]
Why?

**Comment by chtyim** [comment]
We shouldn't change to twill snapshot. And it's too late to start releasing twill and test with cdap

**Comment by anwar6953** [comment]
Twill 0.7.0 was one of the release dependencies.
CDAP 3.3.0 will release without it, you're saying?

**Comment by chtyim** [comment]
Right. I thought we agreed to keep using twill 0.6.0 for CDAP 3.3.0 release

**Comment by anwar6953** [comment]
Closing PR, as we're keeping twill 0.6 for CDAP 3.3.

**Pull request closed without merging**
