### PR TITLE
Update to use Twill release version

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by prinam** [comment]
LGTM

**Comment by gsps1** [comment]
@chtyim can you remove the snapshot repo as well ?

**Comment by gsps1** [comment]
https://issues.cask.co/browse/CDAP-2914

**Comment by gsps1** [comment]
LGTM

**Comment by chtyim** [comment]
Build failed with the know LogAnalysisAppTest only. Since that test is fixed in release, will just merge this one.

**Pull request merged**
