### PR TITLE
(CDAP-3786) Document the configuration needed for running Spark in HDP2.2+

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by wolf31o2** [comment]
Do we not need the accompanying spark.driver property?

http://hortonworks.com/community/forums/topic/yarn-spark-submit-failure/#post-65158

**Comment by chtyim** [comment]
That we don't. Currently the twill container we launched is the driver, which already have the hdp.version set.

**Comment by wolf31o2** [comment]
:+1: LGTM

**Comment by chtyim** [comment]
Resolved merge conflict since the section get moved to a different file.

**Pull request merged**
