### PR TITLE
Set 'localhost:10000' as the default instanceUri. Also updated an inc…

### PR DESCRIPTION
**Pull request by bdmogal**
…orrect javadoc for instanceUri.

Reduces 1 extra step while writing integration tests.

Build: http://builds.cask.co/browse/CDAP-RBT607

### CODE REVIEW

**Comment by anwar6953** [comment]
LGTM

**Comment by anwar6953** [comment]
I think you have to explicitly specify the `http://`

**Comment by bdmogal** [comment]
Nope, its not needed. Tested it by:
* Removed the ``STANDALONE_TESTER`` and the overriden method ``getInstanceUri()`` in the ``TestSQL`` class and ran it in this branch. 
* Did not pass ``-DinstanceUri`` in the run configuration. 
* ``getInstanceUri()`` returns ``localhost:10000``. Test passes.

**Comment by anwar6953** [comment]
:+1:

**Comment by bdmogal** [comment]
Build passed: http://builds.cask.co/browse/CDAP-RBT607-2. Merging.

**Pull request merged**
