### PR TITLE
CDAP-1861 bump the kafka topic version and parition  of logging for ns

### PR DESCRIPTION
**Pull request by rohitsinha54**
- Bump the version of kafka topic for new schema with namespace
- Increase the number of partitions

Issues: https://issues.cask.co/browse/CDAP-1861

Build: http://builds.cask.co/browse/CDAP-RBT189-1

### CODE REVIEW

**Comment by poornachandra** [comment]
Will clearing the kafka offsets for v1 topic from log.meta table come in a different PR?

**Comment by rohitsinha54** [comment]
I changed the upgrade part to upgrade only the records for logs and not offsets and since it gets written to new table it will be fine.

**Comment by poornachandra** [comment]
You will have to document that old logs will no longer be available in UI. And also wait for log saver to complete processing of of log events in the old format.

**Comment by rohitsinha54** [comment]
Added it in the doc issue here: https://issues.cask.co/browse/CDAP-1803

**Comment by poornachandra** [comment]
LGTM

**Comment by rohitsinha54** [comment]
Build running here : http://builds.cask.co/browse/CDAP-RBT189-2

**Comment by rohitsinha54** [comment]
Build passed here : http://builds.cask.co/browse/CDAP-RBT189-2

**Pull request merged**
