### PR TITLE
(CDAP-1402) Temporary fix for the stream config update race condition

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by anew** [comment]
LGTM

**Comment by chtyim** [comment]
Test running in https://builds.cask.co/browse/CDAP-RBT132-1

**Comment by anew** [comment]
much nicer! like!
LGTM

**Comment by chtyim** [comment]
Test passes in https://builds.cask.co/browse/CDAP-RBT132-2

**Pull request merged**
