### PR TITLE
CDAP-3399: SparkPageRankApp use just one service and simplified test

### PR DESCRIPTION
**Pull request by rohitsinha54**

### CODE REVIEW

**Comment by anwar6953** [comment]
lgtm

**Comment by rohitsinha54** [comment]
Waiting on build: http://builds.cask.co/browse/CDAP-DUT2535-1

**Comment by bdmogal** [comment]
This will need updates to integration tests.

**Comment by rohitsinha54** [comment]
Integration test changes PR: https://github.com/caskdata/cdap-integration-tests/pull/46

**Comment by rohitsinha54** [comment]
These changes also needs to updated in archetype. Will do it in an individual PR.

**Pull request merged**
