### PR TITLE
Feature/expose history on all program managers

### PR DESCRIPTION
**Pull request by anwar6953**
First commit moves the implementation from WorkflowManager to AbstractProgramManager to enable that functionality for all program types.
Second commit simply cleans up redundant castings.

http://builds.cask.co/browse/CDAP-DUT2456-3

### CODE REVIEW

**Comment by bdmogal** [comment]
The code LGTM. However, should we add some unit tests?

**Comment by anwar6953** [comment]
The test case was a good idea; it revealed that AppFabricClient#getHistory was not generic to all program types.
Add test case to test ServiceManager#getHistory and fix AppFabricClient#getHistory to be more generic.

**Comment by anwar6953** [comment]
"So this method was workflow specific?"
Yes.

"don't need the ``status=completed``? This is for completed runs right?"
Only the url had status=completed. The actual call to the handler didn't specify a particular status. This is consistent in both the default as well as remote implementations, so I simply removed that part from the url to also make that consistent.

**Comment by bdmogal** [comment]
> The actual call to the handler didn't specify a particular status. 

Should it, though?

Apart from that, LGTM

**Comment by anwar6953** [comment]
I don't think so. This enables users to retrieve all run records, which is more flexible than simple returning the completed ones.

**Comment by bdmogal** [comment]
But do the underlying usages expect only completed runs? We don't allow users to specify a filter either, right?

**Comment by anwar6953** [comment]
Updated to allow user to specify a filter (ProgramRunStatus).

**Comment by bdmogal** [comment]
LGTM

**Pull request merged**
