### PR TITLE
Documentation Search and 404 pages fixes et al

### PR DESCRIPTION
**Pull request by awholegunch**
Fixes for [CDAP-665](https://issues.cask.co/browse/CDAP-1188), [CDAP-1039](https://issues.cask.co/browse/CDAP-1039): Search and 404 pages

- Adds a revised Search page, with corrected links and clearer information on searching:
  http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_doc_fixes/en/search.html

- Adds a revised 404 page, which links to the search page rather than duplicating its functionality:
  http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_doc_fixes/en/404.html

- Modifies the build script so that the 404 page, when built, uses the branch info to create links.

Fix for [CDAP-1188](https://issues.cask.co/browse/CDAP-1188): Copyright dates
- Updates the copyright signature at the bottom of pages and the code used to generate the license PDFs.

Fix for [CDAP-752](https://issues.cask.co/browse/CDAP-752): Docs should have a section describing how to enable security in CDAP Standalone
- See [Standalone](http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_doc_fixes/en/admin-manual/installation/security.html#enabling-security-standalone-cdap)
and [Distributed](http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_doc_fixes/en/admin-manual/installation/security.html#enabling-security-distributed-cdap)
and [Basic Authentication](http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_doc_fixes/en/admin-manual/installation/security.html#installation-basic-authentication)

Fix for [CDAP-687](https://issues.cask.co/browse/CDAP-1128): “Building Apps” file is not versioned
- See [Deploying an Application](http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_doc_fixes/en/developers-manual/getting-started/building-apps.html#deploying-an-application)

Other fixes:
- Removed an old license file that has been replace by the Apache License. ("LICENSE", located as "cdap-standalone/src/dist/LICENSES/LICENSE")
- Updated the copyright date and some text in the Web-App.
- Added "Standalone CDAP" and "Distributed CDAP" as terms to the Glossary.

### CODE REVIEW

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by awholegunch** [comment]
I'll merge in the morning. I don't want to wait to check that the build is ok...

**Comment by nitinmotgi** [comment]
@awholegunch the first link for google is not working for me. I searched for "Datasets" and all releases and I got nothing from google.

**Comment by awholegunch** [comment]
@nitinmotgi One problem is that the first link is going to search 2.7.0...which is not been indexed yet by Google. If you manually change the search to "2.6.0", you should get results. I expect that once the release gets indexed, the problem disappears.

**Comment by awholegunch** [comment]
@nitinmotgi 
[Search 2.6.0 for Datasets](https://www.google.com/search?hl=en&ie=ISO-8859-1&q=Datasets+site%3Adocs.cask.co%2Fcdap%2F2.7.0+OR+site%3Adocs.cask.co%2Fcdap%2F2.7.0-SNAPSHOT&btnG=Search+this+release+using+Google&gws_rd=ssl#hl=en&q=Datasets+site:docs.cask.co%2Fcdap%2F2.6.0+OR+site:docs.cask.co%2Fcdap%2F2.6.0-SNAPSHOT)
[Search all releases for Datasets](https://www.google.com/search?hl=en&ie=ISO-8859-1&q=Datasets+site%3Adocs.cask.co%2Fcdap&btnG=Search+all+releases+using+Google&gws_rd=ssl)

**Pull request merged**
