### PR TITLE
[ CDAP-3634] Add support for case insensitive search for metadata

### PR DESCRIPTION
**Pull request by henry-cask**
Support metadata search with case insensitive. So search for value "value" and "VaLue" should yields same result.

To do this, we are introducing new column on the metadata index table column to store lower case value and key:value combo.

### CODE REVIEW

**Comment by henry-cask** [comment]
Build:
http://builds.cask.co/browse/CDAP-RBT451-1

**Comment by bdmogal** [comment]
@henry-cask nit: the commit message has the wrong jira. The jira for this is CDAP-3634. Please fix before merging.

**Comment by bdmogal** [comment]
@henry-cask this LGTM. Do you want to add a verification in the ``MetadataHttpHandlerTest`` as well, just for the sake of completion?

**Comment by henry-cask** [comment]
Ah yes, thanks for catching it.

**Comment by henry-cask** [comment]
Build passes: http://builds.cask.co/browse/CDAP-RBT451-1
Merging ...

**Pull request merged**
